Repository microsoft/BotFramework-Composer, pull requests merged in 2019-12, with the labels that each got.

#1738 feat: link to tab
  Composer/packages/client/src/pages/notifications/index.tsx
  Composer/packages/client/src/utils/dialogUtil.ts
  Composer/packages/client/src/utils/navigation.ts
  Composer/packages/lib/indexers/src/dialogUtils/dialogChecker.ts
  Composer/packages/lib/shared/__tests__/convertUtils/parsePathToFocused.test.ts
  Composer/packages/lib/shared/__tests__/convertUtils/parsePathToSelected.test.ts
  Composer/packages/lib/shared/__tests__/convertUtils/parseTypeToFragment.test.ts
  Composer/packages/lib/shared/src/convertUtils/index.ts
  Composer/packages/lib/shared/src/convertUtils/parsePathToFocused.ts
  Composer/packages/lib/shared/src/convertUtils/parsePathToSelected.ts
  Composer/packages/lib/shared/src/convertUtils/parseTypeToFragment.ts
  Composer/packages/lib/shared/src/index.ts
Labels: R7

#1740 ci: disallow opening pr against stable branch unless a release
  .github/actions/conventional-pr/src/conventional-pr.ts
  .github/actions/conventional-pr/src/utils.ts
Labels: R7

#1617 style: Updated Array UI
  Composer/packages/extensions/obiformeditor/__tests__/Form/ArrayFieldTemplate/StringArray.test.tsx
  Composer/packages/extensions/obiformeditor/src/Form/ArrayFieldTemplate/ArrayItem.tsx
  Composer/packages/extensions/obiformeditor/src/Form/ArrayFieldTemplate/ObjectArray.tsx
  Composer/packages/extensions/obiformeditor/src/Form/ArrayFieldTemplate/StringArray.tsx
  Composer/packages/extensions/obiformeditor/src/Form/ArrayFieldTemplate/index.tsx
  Composer/packages/extensions/obiformeditor/src/Form/ArrayFieldTemplate/styles.ts
  Composer/packages/extensions/obiformeditor/src/Form/ObjectFieldTemplate/ObjectItem.tsx
  Composer/packages/extensions/obiformeditor/src/Form/ObjectFieldTemplate/index.tsx
  Composer/packages/extensions/obiformeditor/src/Form/ObjectFieldTemplate/styles.css
  Composer/packages/extensions/obiformeditor/src/Form/fields/BaseField.tsx
  Composer/packages/extensions/obiformeditor/src/Form/fields/CasesField.tsx
  Composer/packages/extensions/obiformeditor/src/Form/fields/CustomObjectField.tsx
  Composer/packages/extensions/obiformeditor/src/Form/fields/EditableField.tsx
  Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/ChoiceInput/Choices.tsx
  Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/Validations.tsx
  Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/styles.ts
  Composer/packages/extensions/obiformeditor/src/Form/fields/RootField.tsx
  Composer/packages/extensions/obiformeditor/src/Form/fields/index.tsx
  Composer/packages/extensions/obiformeditor/src/Form/fields/styles.css
  Composer/packages/extensions/obiformeditor/src/Form/fields/styles.ts
  Composer/packages/extensions/obiformeditor/src/Form/styles.css
  Composer/packages/extensions/obiformeditor/src/Form/types.ts
  Composer/packages/extensions/obiformeditor/src/Form/widgets/ExpressionWidget.tsx
  Composer/packages/extensions/obiformeditor/src/Form/widgets/TextWidget.tsx
  Composer/packages/extensions/obiformeditor/src/FormEditor.tsx
  Composer/packages/extensions/obiformeditor/src/schema/uischema.ts
  Composer/packages/extensions/obiformeditor/src/styles.ts
Labels: R7

#1737 feat: show error message in form editor.
  Composer/packages/client/package.json
  Composer/packages/client/src/pages/language-generation/index.tsx
  Composer/packages/client/src/pages/language-generation/table-view.tsx
  Composer/packages/client/src/utils/dialogUtil.ts
  Composer/packages/extensions/obiformeditor/demo/src/index.tsx
  Composer/packages/extensions/obiformeditor/package.json
  Composer/packages/extensions/obiformeditor/src/Form/types.ts
  Composer/packages/extensions/obiformeditor/src/Form/widgets/ExpressionWidget.tsx
  Composer/packages/extensions/obiformeditor/src/Form/widgets/LgEditorWidget.tsx
  Composer/packages/extensions/obiformeditor/src/FormEditor.tsx
  Composer/packages/lib/code-editor/src/RichEditor.tsx
  Composer/packages/lib/indexers/package.json
  Composer/packages/lib/indexers/src/dialogUtils/dialogChecker.ts
  Composer/packages/lib/indexers/src/lgIndexer.ts
  Composer/packages/lib/indexers/src/type.ts
  Composer/packages/tools/language-servers/language-generation/src/builtinFunctionsMap.ts
  Composer/yarn.lock
Labels: R7

#1735 feat: Update schema and samples
  BotProject/CSharp/Tests/InputsTests.cs
  BotProject/CSharp/Tests/MessageTests.cs
  BotProject/Templates/CSharp/BotProject.csproj
  BotProject/Templates/CSharp/Schemas/sdk.schema
  BotProject/Templates/CSharp/Tests/InputsTests.cs
  BotProject/Templates/CSharp/Tests/MessageTests.cs
  Composer/packages/extensions/obiformeditor/demo/src/editorschema.json
  Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/UserInput.tsx
  Composer/packages/extensions/obiformeditor/src/schema/uischema.ts
  Composer/packages/extensions/visual-designer/src/components/nodes/steps/DefaultRenderer.tsx
  Composer/packages/lib/shared/src/appschema.ts
  Composer/packages/lib/shared/src/labelMap.ts
  Composer/packages/lib/shared/src/types/schema.ts
  Composer/packages/lib/shared/src/viewUtils.ts
  Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/EndDialog/EndDialog.dialog
  Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/HttpRequest/HttpRequest.dialog
  Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/IfCondition/IfCondition.dialog
  Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/ReplaceDialog/Replace.dialog
  Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/TraceAndLog/TraceAndLog.dialog
  Composer/packages/server/assets/projects/AskingQuestionsSample/ComposerDialogs/AttachmentInput/AttachmentInput.dialog
  Composer/packages/server/assets/projects/AskingQuestionsSample/ComposerDialogs/ChoiceInput/ChoiceInput.dialog
  Composer/packages/server/assets/projects/AskingQuestionsSample/ComposerDialogs/NumberInput/NumberInput.dialog
  Composer/packages/server/assets/projects/AskingQuestionsSample/ComposerDialogs/TextInput/TextInput.dialog
  Composer/packages/server/assets/projects/AskingQuestionsSample/ComposerDialogs/common/common.lg
  Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/ForeachPageStep/ForeachPageStep.dialog
  Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/IfCondition/IfCondition.dialog
  Composer/packages/server/assets/projects/InterruptionSample/ComposerDialogs/GetProfile/GetProfile.dialog
  Composer/packages/server/assets/projects/InterruptionSample/ComposerDialogs/common/common.lg
  Composer/packages/server/assets/projects/RespondingWithCardsSample/ComposerDialogs/Main/Main.dialog
  Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/LGComposition/LGComposition.dialog
  Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/LGWithParam/LGWithParam.dialog
  Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/Main/Main.dialog
  Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/TextWithLG/TextWithLG.dialog
  Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/TextWithLG/TextWithLG.lu
  Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/common/common.lg
  Composer/packages/server/assets/projects/ToDoBotWithLuisSample/ComposerDialogs/Main/Main.dialog
  Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/AddToDo/AddToDo.dialog
  Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/DeleteToDo/DeleteToDo.dialog
  Composer/packages/server/schemas/editor.schema
  Composer/packages/server/schemas/sdk.schema
Labels: Status: WIP

#1787 chore: upgrade vscode-eslint
  .vscode/settings.json
Labels: Type: Enhancement

#1756 chore: refactor lg page route & url
  Composer/cypress/integration/LGPage.spec.ts
  Composer/cypress/integration/NotificationPage.spec.ts
  Composer/packages/client/src/pages/language-generation/code-editor.tsx
  Composer/packages/client/src/pages/language-generation/index.tsx
  Composer/packages/client/src/pages/language-generation/table-view.tsx
  Composer/packages/client/src/pages/notifications/index.tsx
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/utils/lgUtil.ts
  Composer/packages/extensions/obiformeditor/src/Form/widgets/LgEditorWidget.tsx
  Composer/packages/lib/indexers/src/type.ts
Labels: Area: LG, Needs review
