Repository microsoft/BotFramework-Composer, pull requests merged in 2020-05, with the labels that each got.

#2872 docs: update usage of $ instead of @, equal sign when assigning
  docs/tutorial/tutorial-get-weather.md
Labels: Approved to merge

#2913 fix: can not capture events in visual editor
  Composer/packages/client/src/pages/design/styles.ts
Labels: Approved to merge

#2921 fix: property editor is slow
  Composer/packages/client/src/pages/design/PropertyEditor.tsx
Labels: Approved to merge

#2899 chore: Component Governance
  Composer/package.json
  Composer/packages/client/package.json
  Composer/packages/electron-server/package.json
  Composer/packages/server/package.json
  Composer/plugins/localPublish/package.json
  Composer/plugins/localPublish/yarn.lock
  Composer/plugins/mockRemotePublish/package.json
  Composer/plugins/mockRemotePublish/yarn.lock
  Composer/plugins/mongoStorage/package-lock.json
  Composer/plugins/mongoStorage/package.json
  Composer/plugins/mongoStorage/yarn.lock
  Composer/yarn.lock
  azure-pipelines.yml
Labels: Approved to merge

#2917 chore: Update trigger wizard
  Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
  Composer/packages/client/src/utils/dialogUtil.ts
Labels: Not Target Master

#2929 a11y: add ARIA landmarks for navigation regions
  Composer/packages/client/src/pages/design/index.tsx
  Composer/packages/client/src/pages/home/index.tsx
  Composer/packages/client/src/pages/language-generation/index.tsx
  Composer/packages/client/src/pages/language-understanding/index.tsx
  Composer/packages/client/src/pages/notifications/NotificationList.tsx
  Composer/packages/client/src/pages/publish/index.tsx
  Composer/packages/client/src/pages/setting/index.tsx
  Composer/packages/client/src/pages/skills/index.tsx
Labels: Approved to merge

#2906 fix: use default runtime when runtime field not defined in settings.json
  Composer/plugins/localPublish/src/index.ts
Labels: Approved to merge

#2939 fix: update some behaviors of showing error message in lu editor
  Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
  Composer/packages/client/src/pages/language-understanding/code-editor.tsx
  Composer/packages/lib/code-editor/src/constants.ts
Labels: Approved to merge

#2785 a11y: focus move around composer, visual editor & form editor when click tab.
  Composer/packages/extensions/visual-designer/src/components/lib/KeyboardZone.tsx
  Composer/packages/extensions/visual-designer/src/editors/ObiEditor.tsx
Labels: Approved to merge

#2954 fix: update bf-lu version to 4.9.0-RC4
  Composer/packages/client/package.json
  Composer/packages/lib/bot-deploy/package.json
  Composer/packages/lib/indexers/package.json
  Composer/packages/server/package.json
  Composer/packages/tools/language-servers/language-understanding/package.json
  Composer/yarn.lock
Labels: Approved to merge

#2984 fix: update bf-lu version to 4.9.0-RC6
  Composer/packages/client/package.json
  Composer/packages/lib/bot-deploy/package.json
  Composer/packages/lib/indexers/package.json
  Composer/packages/server/package.json
  Composer/packages/tools/language-servers/language-understanding/package.json
  Composer/yarn.lock
Labels: Approved to merge

#2963 fix: make array parsing kinder
  Composer/packages/client/src/pages/design/exportSkillModal/constants.tsx
  Composer/packages/client/src/pages/design/exportSkillModal/content/Description.tsx
  Composer/plugins/samples/assets/projects/RespondingWithTextSample/language-generation/en-us/common.en-us.lg
Labels: Approved to merge

#2969 fix: cache the url to keep the page live
  Composer/packages/client/src/App.tsx
  Composer/packages/client/src/components/NavItem/index.tsx
  Composer/packages/client/src/pages/design/index.tsx
  Composer/packages/client/src/utils/hooks.ts
  Composer/packages/client/src/utils/pageLinks.ts
  Composer/packages/client/src/utils/routerCache.ts
Labels: Approved to merge

#2980 feat: Show location in recent bots list
  Composer/packages/client/src/pages/home/RecentBotList.tsx
Labels: Approved to merge

#2985 fix: update botProject in server cache after eject
  Composer/packages/server/src/controllers/eject.ts
  Composer/packages/server/src/models/bot/botProject.ts
Labels: Approved to merge

#2995 a11y: add border to home-page buttons
  Composer/packages/client/src/pages/home/index.tsx
  Composer/packages/client/src/pages/home/styles.ts
Labels: Approved to merge

#3003 chore: update resultProperty descption of http request step
  Composer/packages/server/schemas/sdk.schema
  runtime/dotnet/azurewebapp/Schemas/sdk.schema
Labels: Approved to merge

#3002 fix: lu/lg editor update strategy
  Composer/packages/lib/code-editor/src/BaseEditor.tsx
  Composer/packages/lib/code-editor/src/LgEditor.tsx
  Composer/packages/lib/code-editor/src/LuEditor.tsx
  Composer/packages/ui-plugins/lg/src/LgField.tsx
  Composer/packages/ui-plugins/luis/src/LuisIntentEditor.tsx
Labels: Approved to merge

#3016 fix: open bot read property 'sdk' is undefined
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/store/action/navigation.ts
Labels: Approved to merge

#3018 fix: update lu related packages to released version
  Composer/packages/client/package.json
  Composer/packages/lib/bot-deploy/package.json
  Composer/packages/lib/indexers/package.json
  Composer/packages/server/package.json
  Composer/packages/tools/language-servers/language-understanding/package.json
  Composer/yarn.lock
Labels: Approved to merge

#3025 fix: Maximum call stack size exceeded when open a bot
  Composer/packages/client/src/store/reducer/index.ts
  Composer/packages/lib/shared/__tests__/schemaUtils/circular.test.ts
  Composer/packages/lib/shared/__tests__/schemaUtils/dereference.test.ts
  Composer/packages/lib/shared/__tests__/schemaUtils/getRef.test.ts
  Composer/packages/lib/shared/src/schemaUtils/circular.ts
  Composer/packages/lib/shared/src/schemaUtils/dereference.ts
  Composer/packages/lib/shared/src/schemaUtils/getRef.ts
  Composer/packages/lib/shared/src/schemaUtils/types.ts
Labels: Approved to merge

#3051 fix: Unable to open another bot
  Composer/packages/client/src/pages/design/index.tsx
Labels: Approved to merge

#3038 fix: make tag parsing work better
  Composer/packages/client/src/pages/design/exportSkillModal/content/Description.tsx
Labels: Approved to merge

#3069 fix: duplicated key in recent bot list
  Composer/packages/client/src/pages/home/RecentBotList.tsx
Labels: Approved to merge

#3067 fix: remove cache when getProjectById
  Composer/packages/client/src/components/SkillForm/CreateSkillModal/index.tsx
  Composer/packages/client/src/components/SkillForm/CreateSkillModal/styles.ts
  Composer/packages/lib/indexers/src/utils/diagnosticUtil.ts
  Composer/packages/server/src/models/bot/skillManager.ts
  Composer/packages/server/src/services/project.ts
Labels: Approved to merge

#3117 fix: Include settings changes in persistence layer and flush changes before switching bot
  Composer/packages/client/src/components/CreationFlow/index.tsx
  Composer/packages/client/src/constants/index.ts
  Composer/packages/client/src/pages/setting/dialog-settings/index.tsx
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/store/action/lg.ts
  Composer/packages/client/src/store/action/lu.ts
  Composer/packages/client/src/store/action/project.ts
  Composer/packages/client/src/store/action/setting.ts
  Composer/packages/client/src/store/index.tsx
  Composer/packages/client/src/store/parsers/baseWorker.ts
  Composer/packages/client/src/store/persistence/FilePersistence.ts
  Composer/packages/client/src/store/persistence/types.ts
  Composer/packages/client/src/store/reducer/index.ts
  Composer/packages/client/src/store/types.ts
  Composer/packages/client/src/styles.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/models/settings/fileSettingManager.ts
  Composer/packages/server/src/models/settings/interface.ts
  Composer/packages/server/src/router/api.ts
Labels: Approved to merge

#3141 fix: lg file mess up
  Composer/packages/client/package.json
  Composer/packages/lib/indexers/__tests__/lgUtil.test.ts
  Composer/packages/lib/indexers/package.json
  Composer/packages/lib/indexers/src/dialogUtils/validation.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/tools/language-servers/language-generation/package.json
  Composer/yarn.lock
Labels: Approved to merge

#3197 fix: ignore runtime folder zipping when local publish
  Composer/plugins/localPublish/src/index.ts
Labels: Approved to merge

#3155 refactor: clean some code
  Composer/packages/server/__tests__/models/bot/botProject.test.ts
  Composer/packages/server/__tests__/models/storage/azureBlobStorage.test.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/models/storage/azureBlobStorage.ts
  Composer/packages/server/src/models/storage/interface.ts
  Composer/packages/server/src/models/storage/localDiskStorage.ts
  Composer/plugins/mongoStorage/src/index.ts
Labels: Approved to merge

#3210 test: create option test cases
  Composer/packages/client/__tests__/components/CreationFlow/CreateOptions/index.test.tsx
Labels: Approved to merge

#3238 fix: update expression and publish doc links
  Composer/packages/client/src/pages/setting/dialog-settings/index.tsx
  Composer/packages/ui-plugins/expressions/src/index.ts
Labels: Needs review
