Repository microsoft/BotFramework-Composer, pull requests merged in 2020-10, with the labels that each got.

#4296 feat: form dialog extension
  Composer/package.json
  Composer/packages/form-dialogs/.eslintrc.js
  Composer/packages/form-dialogs/.gitignore
  Composer/packages/form-dialogs/package.json
  Composer/packages/form-dialogs/src/FormDialogSchemaEditor.tsx
  Composer/packages/form-dialogs/src/atoms/appState.ts
  Composer/packages/form-dialogs/src/atoms/handlers.ts
  Composer/packages/form-dialogs/src/atoms/types.ts
  Composer/packages/form-dialogs/src/atoms/utils.ts
  Composer/packages/form-dialogs/src/components/FormDialogPropertiesEditor.tsx
  Composer/packages/form-dialogs/src/components/common/Collapsible.tsx
  Composer/packages/form-dialogs/src/components/common/CommandBarUpload.tsx
  Composer/packages/form-dialogs/src/components/common/FieldLabel.tsx
  Composer/packages/form-dialogs/src/components/common/HelpTooltip.tsx
  Composer/packages/form-dialogs/src/components/common/ValuePicker.tsx
  Composer/packages/form-dialogs/src/components/property/AdvancedOptions.tsx
  Composer/packages/form-dialogs/src/components/property/FormDialogPropertyCard.tsx
  Composer/packages/form-dialogs/src/components/property/FormDialogSchemaDetails.tsx
  Composer/packages/form-dialogs/src/components/property/NumberPropertyContent.tsx
  Composer/packages/form-dialogs/src/components/property/PropertyList.tsx
  Composer/packages/form-dialogs/src/components/property/PropertyListItem.tsx
  Composer/packages/form-dialogs/src/components/property/PropertyTypeSelector.tsx
  Composer/packages/form-dialogs/src/components/property/RequiredPriorityIndicator.tsx
  Composer/packages/form-dialogs/src/components/property/StringPropertyContent.tsx
  Composer/packages/form-dialogs/src/components/tags/ContentEditable.tsx
  Composer/packages/form-dialogs/src/components/tags/Tag.tsx
  Composer/packages/form-dialogs/src/components/tags/TagInput.tsx
  Composer/packages/form-dialogs/src/components/tags/utils.ts
  Composer/packages/form-dialogs/src/demo/Demo.tsx
  Composer/packages/form-dialogs/src/demo/DemoApp.tsx
  Composer/packages/form-dialogs/src/demo/index.html
  Composer/packages/form-dialogs/src/demo/stylesheet.css
  Composer/packages/form-dialogs/src/index.ts
  Composer/packages/form-dialogs/src/utils/base.ts
  Composer/packages/form-dialogs/src/utils/constants.ts
  Composer/packages/form-dialogs/src/utils/file.ts
  Composer/packages/form-dialogs/src/utils/hooks/useKeyBinding.ts
  Composer/packages/form-dialogs/src/utils/hooks/useTraceProps.ts
  Composer/packages/form-dialogs/src/utils/hooks/useUndoKeyBinding.ts
  Composer/packages/form-dialogs/tools/devServer.js
  Composer/packages/form-dialogs/tsconfig.json
  Composer/packages/form-dialogs/tsconfig.lib.json
  Composer/packages/form-dialogs/webpack.config.js
  Composer/packages/form-dialogs/webpack.lib.config.js
  Composer/packages/server/src/locales/en-US.json
  Composer/yarn.lock
Labels: Area: Form Dialogs, R11, Team: Authoring

#4321 fix: only show enabled extension pages
  Composer/packages/client/src/recoilModel/index.ts
  Composer/packages/client/src/recoilModel/selectors/extensions.ts
  Composer/packages/client/src/recoilModel/selectors/index.ts
  Composer/packages/client/src/utils/hooks.ts
Labels: Area: Extension, Team: Platform

#4341 chore: Updating to latest version of generate library
  Composer/packages/server/package.json
  Composer/yarn.lock
Labels: Team: Authoring

#3744 feat: BotProject File Schema
  Composer/packages/server/.gitignore
  Composer/packages/server/schemas/botproject.schema
Labels: BotProjects, R11

#4353 feat: Added jsonSchema and trigger content
  Composer/packages/client/__tests__/pages/notifications/useNotifications.test.tsx
  Composer/packages/client/src/pages/notifications/useNotifications.tsx
  Composer/packages/client/src/recoilModel/DispatcherWrapper.tsx
  Composer/packages/client/src/recoilModel/atoms/botState.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/lib/indexers/__tests__/jsonSchemafileIndexer.test.ts
  Composer/packages/lib/indexers/src/dialogIndexer.ts
  Composer/packages/lib/indexers/src/index.ts
  Composer/packages/lib/indexers/src/jsonSchemaFileIndexer.ts
  Composer/packages/lib/indexers/src/skillManifestIndexer.ts
  Composer/packages/lib/indexers/src/utils/fileExtensions.ts
  Composer/packages/server/src/models/bot/__tests__/botProject.test.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/types/src/indexers.ts
Labels: Team: Authoring

#4422 fix: fix publish failure due to runtime template path error
  extensions/runtimes/src/index.ts
Labels: Approved to merge, Team: Runtime & Publishing

#4423 fix: azure publish failed
  Composer/packages/server/package.json
  Composer/yarn.lock
  extensions/azurePublish/package.json
  extensions/azurePublish/src/luisAndQnA.ts
  extensions/azurePublish/yarn.lock
Labels: Approved to merge, Team: Platform, Team: Runtime & Publishing

#4413 feat: Added trigger grouping methods to indexers
  Composer/packages/lib/indexers/src/extractSchemaProperties.ts
  Composer/packages/lib/indexers/src/groupTriggers.ts
  Composer/packages/lib/indexers/src/index.ts
  Composer/packages/types/src/indexers.ts
Labels: Team: Authoring

#4368 feat: Update LG library
  Composer/packages/adaptive-flow/package.json
  Composer/packages/client/src/hooks/useResolver.ts
  Composer/packages/client/src/recoilModel/parsers/workers/lgParser.worker.ts
  Composer/packages/lib/indexers/package.json
  Composer/packages/lib/indexers/src/index.ts
  Composer/packages/lib/indexers/src/utils/lgUtil.ts
  Composer/packages/lib/shared/src/resolverFactory.ts
  Composer/packages/server/src/services/project.ts
  Composer/packages/tools/language-servers/language-generation/package.json
  Composer/packages/tools/language-servers/language-generation/src/LGServer.ts
  Composer/packages/tools/language-servers/language-generation/src/lgParser.ts
  Composer/packages/tools/language-servers/language-generation/src/lgWorker.ts
  Composer/packages/tools/language-servers/language-understanding/src/LUServer.ts
  Composer/packages/tools/language-servers/language-understanding/src/utils.ts
  Composer/yarn.lock
  extensions/azurePublish/yarn.lock
Labels: Approved to merge, Team: Authoring, Team: Platform

#4444 fix: Excluded settings and scripts globs
  Composer/packages/server/src/models/bot/__tests__/botProject.test.ts
  Composer/packages/server/src/models/bot/botProject.ts
Labels: Team: Authoring

#4432 fix: unify create qna from url/scratch window height
  Composer/packages/client/src/components/QnA/CreateQnAFromScratchModal.tsx
  Composer/packages/client/src/components/QnA/styles.ts
Labels: Approved to merge, Team: Authoring

#4384 feat: bf-orchestrator lib integration
  Composer/packages/server/jest.config.js
  Composer/packages/server/package.json
  Composer/packages/server/src/models/bot/__mocks__/mockLUInput.json
  Composer/packages/server/src/models/bot/__tests__/orchestratorBuilder.test.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/models/bot/builder.ts
  Composer/packages/server/src/models/bot/interface.ts
  Composer/yarn.lock
  Dockerfile
Labels: Team: Platform

#4525 fix: Exclude no template definition warning in LG editor
  Composer/packages/lib/indexers/src/lgIndexer.ts
  Composer/packages/tools/language-servers/language-generation/src/utils.ts
Labels: Approved to merge

#4523 ci: Disable docker cache temporarily
  .github/workflows/docker.yml
Labels: Team: Platform

#4499 feat: allow extensions to read/write data
  Composer/packages/electron-server/src/main.ts
  Composer/packages/extension/package.json
  Composer/packages/extension/src/__tests__/setupEnv.ts
  Composer/packages/extension/src/extensionContext.ts
  Composer/packages/extension/src/extensionRegistration.ts
  Composer/packages/extension/src/manager/manager.ts
  Composer/packages/extension/src/storage/__tests__/extensionManifestStore.test.ts
  Composer/packages/extension/src/storage/__tests__/store.test.ts
  Composer/packages/extension/src/storage/extensionManifestStore.ts
  Composer/packages/extension/src/storage/store.ts
  Composer/packages/server/src/controllers/__tests__/publisher.test.ts
  Composer/packages/server/src/server.ts
  Composer/yarn.lock
  Dockerfile
  extensions/README.md
  extensions/sample-ui-plugin/src/node/index.ts
  extensions/sample-ui-plugin/yarn.lock
Labels: Area: Extension, Team: Platform

#4537 fix: Add form-wide and better trigger grouping
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/lib/indexers/src/groupTriggers.ts
Labels: Team: Authoring

#4520 chore: update server api to prevent overwrite the root dialog
  Composer/packages/server/src/controllers/project.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/models/bot/botStructure.ts
Labels: Approved to merge, Team: Platform

#4545 perf: don't call Shell API when Flow Editor focused element not changed
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useEditorEventApi.ts
Labels: Approved to merge

#4553 fix: Add delete form dialog to Composer server API
  Composer/packages/server/src/controllers/formDialog.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/router/api.ts
Labels: Team: Authoring

#4574 fix: Adds validation for form dialogs propery name
  Composer/packages/form-dialogs/src/FormDialogSchemaEditor.tsx
  Composer/packages/form-dialogs/src/atoms/utils.ts
  Composer/packages/form-dialogs/src/components/property/FormDialogPropertyCard.tsx
  Composer/packages/form-dialogs/src/utils/constants.ts
  Composer/packages/server/src/locales/en-US.json
Labels: Area: Form Dialogs, Team: Authoring

#4557 feat: Disable Connect to Skill menu action inside skill
  Composer/packages/adaptive-flow/__tests__/adaptive-flow-editor/renderers/EdgeMenu.test.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/renderers/EdgeMenu/EdgeMenu.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/renderers/EdgeMenu/createSchemaMenu.tsx
  Composer/packages/client/src/shell/useShell.ts
  Composer/packages/extension-client/src/hooks/__tests__/useMenuConfig.test.tsx
  Composer/packages/extension-client/src/hooks/useMenuConfig.ts
  Composer/packages/types/src/shell.ts
Labels: BotProjects, Not Targetting Main, Team: Platform

#4354 doc: guidelines/help-contents
  docs/guidelines/Composer-help-contents.md
  docs/guidelines/media/azure-button.png
  docs/guidelines/media/azure-helplink.png
  docs/guidelines/media/azure-menu.png
  docs/guidelines/media/azure-tooltip.png
  docs/guidelines/media/azure-watermark.png
  docs/guidelines/media/composer-error-message.png
  docs/guidelines/media/pva-instructional-copy.png
  docs/guidelines/media/pva-modal-button.png
  docs/guidelines/media/vm-helplink.png
Labels: approved
