Repository microsoft/BotFramework-Composer, pull requests merged in 2020-12, with the labels that each got.

#4494 feat: Updated js runtime to use the latest SDK
  extensions/runtimes/src/index.ts
  runtime/node/__tests__/actions.test.ts
  runtime/node/__tests__/controllingConversation.test.ts
  runtime/node/__tests__/inputs.test.ts
  runtime/node/__tests__/message.test.ts
  runtime/node/__tests__/todobot.test.ts
  runtime/node/package.json
  runtime/node/schemas/readme.md
  runtime/node/schemas/sdk.schema
  runtime/node/schemas/sdk.uischema
  runtime/node/schemas/update-schema.ps1
  runtime/node/schemas/update-schema.sh
  runtime/node/src/customaction/MultiplyDialog.schema
  runtime/node/src/customaction/customActionComponentRegistration.ts
  runtime/node/src/customaction/multiplyDialog.ts
  runtime/node/src/shared/composerBot.ts
  runtime/node/src/shared/helpers.ts
Labels: 1.3

#5011 feat: azure publish with orchestrator
  Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/models/bot/builder.ts
  extensions/azurePublish/package.json
  extensions/azurePublish/src/deploy.ts
  extensions/azurePublish/src/index.ts
  extensions/azurePublish/src/luisAndQnA.ts
  extensions/azurePublish/src/utils/crossTrainUtil.ts
  extensions/azurePublish/src/utils/fileUtil.ts
  extensions/azurePublish/src/utils/jsonWalk.ts
Labels: 1.3

#5062 fix: Update bf-generate-library to fix merging and string property issues
  Composer/packages/client/src/recoilModel/dispatchers/formDialogs.ts
  Composer/packages/server/package.json
  Composer/yarn.lock
Labels: Area: Form Dialogs

#5061 fix: Start bots panel design and error popup issues
  Composer/cypress/integration/LuisDeploy.spec.ts
  Composer/cypress/support/index.ts
  Composer/packages/client/__tests__/components/header.test.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotControllerMenu.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotRuntimeStatus.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotStatusIndicator.tsx
  Composer/packages/client/src/components/__tests__/BotRuntimeController/BotRuntimeStatus.test.tsx
  Composer/packages/client/src/components/__tests__/BotRuntimeController/BotStatusIndicator.test.tsx
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/utils/hooks.ts
Labels: 1.3, BotProjects

#5069 chore: Remove fit for tests
  Composer/packages/adaptive-flow/__tests__/adaptive-flow-editor/renderers/EdgeMenu.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/botProjectFile.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/skill.test.ts
Labels: 1.3

#5012 fix: some bug fix about publish page
  Composer/packages/client/src/pages/publish/Publish.tsx
Labels: 1.3, BotProjects

#5068 fix: Install 64-bit vcredist package
  Composer/packages/electron-server/resources/installer.nsh
Labels: 1.3

#5079 feat: Disable stop all operations while start operations is being performed
  Composer/cypress/integration/LuisDeploy.spec.ts
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/Header.tsx
  Composer/packages/client/src/components/__tests__/BotRuntimeController/BotController.test.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/pages/setting/SettingsPage.tsx
Labels: 1.3, BotProjects

#4968 feat: telemetry api
  Composer/cypress/integration/ToDoBot.spec.ts
  Composer/cypress/support/index.ts
  Composer/packages/client/__tests__/components/CreationFlow/index.test.tsx
  Composer/packages/client/__tests__/components/appSettings.test.tsx
  Composer/packages/client/src/App.tsx
  Composer/packages/client/src/components/AppComponents/Assistant.tsx
  Composer/packages/client/src/components/DataCollectionDialog.tsx
  Composer/packages/client/src/pages/setting/app-settings/AppSettings.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/serverSettings.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/user.test.ts
  Composer/packages/client/src/recoilModel/dispatchers/index.ts
  Composer/packages/client/src/recoilModel/dispatchers/serverSettings.tsx
  Composer/packages/client/src/recoilModel/dispatchers/user.ts
  Composer/packages/client/src/recoilModel/types.ts
  Composer/packages/client/src/recoilModel/utils/index.ts
  Composer/packages/client/src/telemetry/AppInsightsClient.ts
  Composer/packages/client/src/telemetry/ConsoleClient.ts
  Composer/packages/client/src/telemetry/TelemetryClient.ts
  Composer/packages/client/src/telemetry/__tests__/AppInsightsClient.test.ts
  Composer/packages/client/src/telemetry/__tests__/TelemetryClient.test.ts
  Composer/packages/client/src/telemetry/useInitializeLogger.ts
  Composer/packages/electron-server/__tests__/utility/machineId.test.ts
  Composer/packages/electron-server/package.json
  Composer/packages/electron-server/src/main.ts
  Composer/packages/electron-server/src/utility/getMacAddress.ts
  Composer/packages/electron-server/src/utility/machineId.ts
  Composer/packages/server/package.json
  Composer/packages/server/src/constants.ts
  Composer/packages/server/src/controllers/telemetry.ts
  Composer/packages/server/src/router/api.ts
  Composer/packages/server/src/services/telemetry.ts
  Composer/packages/server/src/utility/electronContext.ts
  Composer/packages/types/src/settings.ts
  Composer/packages/types/src/telemetry.ts
  Composer/yarn.lock
Labels: 1.3

#5070 fix: QnA and project tree UX from botprojects
  Composer/packages/client/src/components/Page.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/components/QnA/CreateQnAFromScratchModal.tsx
  Composer/packages/client/src/pages/knowledge-base/QnAPage.tsx
  Composer/packages/client/src/pages/language-generation/LGPage.tsx
  Composer/packages/client/src/pages/language-understanding/LUPage.tsx
  Composer/packages/client/src/recoilModel/dispatchers/qna.ts
  Composer/packages/client/src/recoilModel/selectors/diagnosticsPageSelector.ts
Labels: 1.3

#5032 fix: Lg content missing when switch the page
  Composer/packages/client/src/recoilModel/dispatchers/lg.ts
  Composer/packages/client/src/recoilModel/parsers/lgDiagnosticWorker.ts
  Composer/packages/client/src/recoilModel/parsers/workers/lgParserDiagnostic.worker.ts
  Composer/packages/tools/language-servers/language-generation/src/LGServer.ts
  Composer/packages/tools/language-servers/language-generation/src/lgParser.ts
  Composer/packages/tools/language-servers/language-generation/src/lgWorker.ts
  Composer/packages/tools/language-servers/language-generation/src/utils.ts
Labels: 1.3

#5092 chore: Upgrade Orchestrator Lib packages
  Composer/packages/electron-server/electron-builder-config.json
  Composer/packages/server/package.json
  Composer/packages/server/src/models/bot/builder.ts
  Composer/yarn.lock
Labels: 1.3, Area: Orchestrator

#5116 fix: Allow manifest creation on root bot
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
Labels: 1.3, BotProjects

#5195 feat: Added FeatureFlagChanged to telemetry
  Composer/packages/client/src/recoilModel/dispatchers/storage.ts
  Composer/packages/types/src/telemetry.ts
Labels: Team: Authoring

#5197 fix: Minor Orchestrator Text Changes
  Composer/packages/lib/shared/src/featureFlagUtils/index.ts
  Composer/packages/ui-plugins/orchestrator/src/index.ts
Labels: Area: Orchestrator, R11 Bugbash

#5201 fix: UX improvement to form dialogs and updated library
  Composer/packages/client/src/Onboarding/Onboarding.tsx
  Composer/packages/client/src/pages/botProject/DeleteBotButton.tsx
  Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/pages/form-dialog/FormDialogPage.tsx
  Composer/packages/client/src/pages/form-dialog/FormDialogSchemaList.tsx
  Composer/packages/client/src/pages/form-dialog/FormDialogSchemaListHeader.tsx
  Composer/packages/client/src/pages/form-dialog/VisualFormDialogSchemaEditor.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/dispatchers/formDialogs.ts
  Composer/packages/client/src/shell/useShell.ts
  Composer/packages/form-dialogs/package.json
  Composer/packages/form-dialogs/src/components/FormDialogPropertiesEditor.tsx
  Composer/packages/form-dialogs/src/components/property/PropertyListItem.tsx
  Composer/packages/form-dialogs/src/components/tags/TagInput.tsx
  Composer/packages/lib/shared/src/featureFlagUtils/index.ts
  Composer/packages/lib/ui-shared/src/components/ConfirmDialog.tsx
  Composer/packages/lib/ui-shared/src/components/index.ts
  Composer/packages/server/package.json
  Composer/yarn.lock
  docs/preview features/form-dialogs.md
Labels: 1.3, Area: Form Dialogs

#5204 fix: preserve selection when selecting right to left
  Composer/packages/adaptive-form/src/components/fields/StringField.tsx
Labels: 1.3

#4640 fix: update powershell script to support qna and corsstrain build
  runtime/dotnet/azurewebapp/Scripts/deploy.ps1
  runtime/dotnet/azurewebapp/Scripts/readme.md
Labels: 1.3

#5213 fix: Allowed Callers list instantiated to an empty string array.
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/server/package.json
  Composer/packages/server/src/models/settings/defaultSettingManager.ts
  Composer/packages/server/src/server.ts
  Composer/yarn.lock
  extensions/localPublish/package.json
  extensions/localPublish/src/index.ts
  extensions/localPublish/yarn.lock
  runtime/dotnet/azurewebapp/Authorization/AllowedCallersClaimsValidator.cs
  runtime/dotnet/tests/AllowedCallersClaimsValidationTests.cs
Labels: 1.3, BotProjects

#5240 fix: Detect older versions of VCRedist properly
  Composer/packages/electron-server/resources/installer.nsh
Labels: 1.3, Area: Orchestrator, R11 Bugbash

#5242 feat: Restart all bots
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotControllerMenu.tsx
  Composer/packages/client/src/components/BotRuntimeController/useBotOperations.ts
  Composer/packages/client/src/components/Header.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/components/__tests__/BotRuntimeController/BotController.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/recoilModel/selectors/localRuntimeBuilder.ts
Labels: 1.3, BotProjects

#5247 fix: Show panel only if previous status is not restart all bots
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
Labels: 1.3, BotProjects

#5241 chore: Upgrade orchestrator-core
  Composer/packages/server/package.json
  Composer/yarn.lock
Labels: 1.3, Area: Orchestrator

#5196 feat: add extension settings
  .vscode/settings.json
  Composer/packages/client/src/components/PluginHost/PluginHost.tsx
  Composer/packages/client/src/pages/extensions/ExtensionSearchResults.tsx
  Composer/packages/client/src/pages/extensions/ExtensionsPage.tsx
  Composer/packages/client/src/pages/extensions/ExtensionsSettings.tsx
  Composer/packages/client/src/pages/extensions/InstallExtensionDialog.tsx
  Composer/packages/client/src/pages/setting/router.tsx
  Composer/packages/client/src/plugin-host-preload.ts
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/dispatchers/extensions.ts
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/types/window.d.ts
  Composer/packages/client/src/utils/pageLinks.ts
  Composer/packages/extension-client/src/hooks/index.ts
  Composer/packages/extension-client/src/hooks/useExtensionSettings.ts
  Composer/packages/extension-client/src/types/window.d.ts
  Composer/packages/extension-client/src/utils/validateHookContext.ts
  Composer/packages/extension/src/extensionRegistration.ts
  Composer/packages/lib/code-editor/src/JsonEditor.tsx
  Composer/packages/server/src/controllers/extensions.ts
  Composer/packages/server/src/router/api.ts
  Composer/packages/server/src/services/extensionManager.ts
  Composer/packages/server/src/settings/env.ts
  Composer/packages/server/src/settings/index.ts
  Composer/packages/server/src/store/store.ts
  Composer/packages/types/src/extension.ts
  Composer/packages/types/src/extensionRegistration.ts
  extensions/packageManager/package.json
  extensions/packageManager/src/node/index.ts
  extensions/sample-ui-plugin/package.json
  extensions/sample-ui-plugin/src/client/page/index.tsx
  extensions/sample-ui-plugin/src/shared/settings.ts
  extensions/sample-ui-plugin/src/shared/types.ts
Labels: Area: Extension, Not Targetting Main

#5266 fix: single bot and multi bot context handled
  Composer/cypress/integration/LuisDeploy.spec.ts
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotControllerMenu.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotRuntimeStatus.tsx
  Composer/packages/client/src/components/BotRuntimeController/loading.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/components/__tests__/BotRuntimeController/BotRuntimeStatus.test.tsx
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
  Composer/packages/client/src/recoilModel/selectors/localRuntimeBuilder.ts
  Composer/yarn.lock
Labels: 1.3, BotProjects

#5275 chore: Remove Orchestrator pdbs from Azure publish flow
  extensions/azurePublish/src/deploy.ts
Labels: 1.3, Area: Orchestrator

#5278 fix: Azure functions deployment and code.zip size doubled issue
  extensions/runtimes/src/index.ts
Labels: Approved to merge

#5282 revert: Remove Orchestrator pdbs from Azure publish flow
  extensions/azurePublish/src/deploy.ts
Labels: 1.3, Area: Orchestrator

#5288 fix: Start bots optimization
  extensions/localPublish/src/index.ts
Labels: 1.3, BotProjects

#5289 fix: Fetch merged settings on reload
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
Labels: 1.3, BotProjects

#5077 fix: composer SDK runtime loading adaptive dialogs failing for dialogs that has loop in it.
  runtime/dotnet/core/ComposerBot.cs
Labels: 1.3

#5283 chore: Update en-US.json with latest string changes
  Composer/packages/server/src/locales/en-US.json
Labels: 1.3

#5291 chore: Remove onnxruntime.pdb from Publishing
  runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
Labels: 1.3, Area: Orchestrator

#5313 fix: runtime throw exception when there is no cosmosdb config
  extensions/azurePublish/src/luisAndQnA.ts
  runtime/dotnet/azurewebapp/Startup.cs
Labels: 1.3

#5314 fix: surface dotnet build error on runtime
  Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
Labels: 1.3

#5322 fix: Start panel open on start/restart operation
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/recoilModel/selectors/localRuntimeBuilder.ts
Labels: 1.3

#5384 fix: improve type-safety of server code
  Composer/packages/server/package.json
  Composer/packages/server/src/controllers/__tests__/auth.test.ts
  Composer/packages/server/src/controllers/asset.ts
  Composer/packages/server/src/externalContentProvider/externalContentProvider.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/models/bot/builder.ts
  Composer/packages/server/src/models/bot/interface.ts
  Composer/packages/server/src/models/settings/defaultSettingManager.ts
  Composer/packages/server/src/models/settings/fileSettingManager.ts
  Composer/packages/server/src/services/project.ts
  Composer/packages/server/src/settings/env.ts
  Composer/packages/server/src/store/migrations.ts
  Composer/packages/server/src/utility/attachLSP.ts
  Composer/packages/server/src/utility/isSubdirectory.ts
  Composer/packages/tools/language-servers/language-understanding/__tests__/helpers/server.ts
  Composer/packages/types/src/indexers.ts
Labels: Team: Platform
