Repository microsoft/BotFramework-Composer, pull requests merged in 2020-07, with the labels that each got.

#3542 chore: adds webpack bundle analyzer
  Composer/packages/client/config/webpack.config.js
  Composer/packages/client/package.json
  Composer/yarn.lock
Labels: Approved to merge

#3525 refactor: split some actions off setSettings
  Composer/cypress/integration/NotificationPage.spec.ts
  Composer/cypress/support/commands.ts
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/pages/publish/index.tsx
  Composer/packages/client/src/pages/setting/dialog-settings/index.tsx
  Composer/packages/client/src/pages/setting/runtime-settings/index.tsx
  Composer/packages/client/src/store/action/eject.ts
  Composer/packages/client/src/store/action/setting.ts
  Composer/packages/client/src/store/persistence/FilePersistence.ts
  Composer/packages/client/src/store/reducer/index.ts
  Composer/packages/server/__tests__/controllers/project.test.ts
  Composer/packages/server/__tests__/services/project.test.ts
  Composer/packages/server/src/services/project.ts
Labels: Approved to merge

#3537 fix: Dialog validate throw error when delete an action
  Composer/packages/lib/indexers/__tests__/validations/expressionValidation.test.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/index.ts
  Composer/packages/lib/shared/src/types/indexers.ts
Labels: Approved to merge

#3550 fix: composer will crashed when add a new publish profile
  Composer/packages/client/src/store/action/setting.ts
  Composer/packages/client/src/store/persistence/FilePersistence.ts
Labels: Approved to merge

#3557 fix: deploy issue while zipping the folder
  Composer/package.json
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/store/action/eject.ts
  Composer/packages/client/src/store/action/setting.ts
  Composer/packages/client/src/store/index.tsx
  Composer/packages/client/src/store/persistence/FilePersistence.ts
  Composer/packages/client/src/store/reducer/index.ts
  Composer/packages/client/src/store/types.ts
  Composer/packages/electron-server/package.json
  Composer/packages/electron-server/scripts/copy-plugins.js
  Composer/packages/lib/package.json
  Composer/plugins/azureFunctionsPublish/package.json
  Composer/plugins/azureFunctionsPublish/src/index.ts
  Composer/plugins/azureFunctionsPublish/yarn.lock
  Composer/plugins/azurePublish/package.json
  Composer/plugins/azurePublish/src/index.ts
  Composer/plugins/lib/bot-deploy/.gitignore
  Composer/plugins/lib/bot-deploy/README.md
  Composer/plugins/lib/bot-deploy/package.json
  Composer/plugins/lib/bot-deploy/src/botProjectDeploy.ts
  Composer/plugins/lib/bot-deploy/src/botProjectDeployConfig.ts
  Composer/plugins/lib/bot-deploy/src/botProjectLoggerType.ts
  Composer/plugins/lib/bot-deploy/src/index.ts
  Composer/plugins/lib/bot-deploy/tsconfig.json
  Composer/plugins/lib/package.json
  Composer/plugins/localPublish/yarn.lock
  Composer/plugins/package.json
  Composer/plugins/samples/yarn.lock
  Composer/plugins/yarn.lock
Labels: Approved to merge

#3635 fix: the luis settings sometimes are lost when publishing luis
  Composer/packages/client/__tests__/components/TestController/publish-luis-modal.test.jsx
  Composer/packages/client/__tests__/components/skill.test.tsx
  Composer/packages/client/src/components/TestController/TestController.tsx
  Composer/packages/client/src/components/TestController/publishDialog.tsx
  Composer/packages/client/src/pages/language-understanding/publish-luis-modal.jsx
  Composer/packages/client/src/pages/language-understanding/styles.ts
  Composer/packages/client/src/store/action/lu.ts
  Composer/packages/client/src/store/index.tsx
  Composer/packages/client/src/store/types.ts
  Composer/packages/server/src/controllers/project.ts
  Composer/packages/server/src/models/bot/botProject.ts
Labels: Approved to merge

#3597 chore: upgrade Fabric/Fluent and relatives to 7.121
  Composer/packages/client/package.json
  Composer/packages/client/src/store/reducer/index.ts
  Composer/packages/extensions/adaptive-form/src/components/fields/__tests__/NumberField.test.tsx
  Composer/yarn.lock
Labels: R10

#3661 fix: set deleteOldVersion to true when publishing luis
  Composer/packages/server/src/models/bot/luPublisher.ts
Labels: Approved to merge

#3651 doc: home page text
  Composer/packages/client/src/pages/about/About.tsx
  Composer/packages/client/src/pages/home/Home.tsx
Labels: Needs review

#3751 fix: composer loading bot forever due to unexpected main dialog
  Composer/packages/client/src/pages/design/createDialogModal.tsx
  Composer/packages/server/__tests__/models/bot/botProject.test.ts
  Composer/packages/server/src/models/bot/botProject.ts
Labels: Approved to merge
