Repository microsoft/BotFramework-Composer, pull requests merged in 2020-11, with the labels that each got.

#4666 fix: Test/Start buttons unable to click.
  Composer/packages/client/src/components/Notifications/NotificationContainer.tsx
Labels: Approved to merge

#4672 fix: Visual canvas mess up when add new actions in a zoom in/out mode
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/components/ElementMeasurer.tsx
Labels: Approved to merge

#4670 fix: optimize the search experience in ProjectTree
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
Labels: Approved to merge

#4736 fix: correct URL when switching page modes
  Composer/packages/client/src/pages/knowledge-base/QnAPage.tsx
  Composer/packages/client/src/pages/language-generation/LGPage.tsx
  Composer/packages/client/src/pages/language-understanding/LUPage.tsx
  Composer/packages/client/src/utils/hooks.ts
  Composer/packages/client/src/utils/pageLinks.ts
  Composer/packages/server/src/__mocks__/samplebots/bot1/settings/appsettings.json
Labels: BotProjects, Team: Authoring

#4457 feat: Diagnostics Page
  Composer/cypress/integration/NotificationPage.spec.ts
  Composer/packages/client/__tests__/components/notificationList.test.jsx
  Composer/packages/client/__tests__/pages/notifications/diagnosticFilter.test.tsx
  Composer/packages/client/__tests__/pages/notifications/diagnosticList.test.tsx
  Composer/packages/client/__tests__/pages/notifications/diagnostics.test.tsx
  Composer/packages/client/src/components/AppComponents/SideBar.tsx
  Composer/packages/client/src/components/BotRuntimeController/warningInfo.tsx
  Composer/packages/client/src/components/NavItem.tsx
  Composer/packages/client/src/components/Pagination.tsx
  Composer/packages/client/src/pages/diagnostics/DiagnosticFilter.tsx
  Composer/packages/client/src/pages/diagnostics/DiagnosticList.tsx
  Composer/packages/client/src/pages/diagnostics/Diagnostics.tsx
  Composer/packages/client/src/pages/diagnostics/types.ts
  Composer/packages/client/src/pages/notifications/NotificationHeader.tsx
  Composer/packages/client/src/pages/notifications/Notifications.tsx
  Composer/packages/client/src/pages/notifications/styles.ts
  Composer/packages/client/src/pages/notifications/useNotifications.tsx
  Composer/packages/client/src/recoilModel/selectors/diagnosticsPageSelector.ts
  Composer/packages/client/src/recoilModel/selectors/index.ts
  Composer/packages/client/src/recoilModel/selectors/messagers.ts
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/utils/pageLinks.ts
Labels: Not Targetting Main

#4754 feat: Undo/Redo support for skills
  Composer/packages/client/src/pages/design/DesignPage.tsx
Labels: BotProjects, Team: Platform

#4440 fix: Remove enforce auto end dialog for skill bots
  runtime/dotnet/core/ComposerBot.cs
Labels: Team: Runtime & Publishing

#4760 fix: zip file can not be deleted
  extensions/azurePublish/src/botProjectDeployConfig.ts
  extensions/azurePublish/src/deploy.ts
  extensions/azurePublish/src/index.ts
  extensions/azurePublish/src/luisAndQnA.ts
  extensions/azurePublish/src/schema.ts
Labels: 1.2-RC

#4792 fix: Await until delete action finishes
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useDialogEditApi.ts
  Composer/packages/client/src/recoilModel/selectors/__test__/project.test.ts
  Composer/packages/lib/shared/__tests__/skillUtils/index.test.ts
Labels: 1.2-RC, Team: Platform

#4492 feat: bot projects skill & context menu
  Composer/cypress/integration/RemoveDialog.spec.ts
  Composer/packages/adaptive-form/src/components/AdaptiveForm.tsx
  Composer/packages/client/__tests__/components/CreationFlow/index.test.tsx
  Composer/packages/client/__tests__/components/createDialogModal.test.tsx
  Composer/packages/client/__tests__/components/design.test.tsx
  Composer/packages/client/__tests__/components/projecttree.test.tsx
  Composer/packages/client/__tests__/shell/triggerApi.test.tsx
  Composer/packages/client/src/components/CreationFlow/CreateOptions.tsx
  Composer/packages/client/src/components/CreationFlow/CreationFlow.tsx
  Composer/packages/client/src/components/CreationFlow/DefineConversation.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx
  Composer/packages/client/src/components/ProjectTree/treeItem.tsx
  Composer/packages/client/src/components/RepairSkillModal.tsx
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/pages/design/ManifestEditor.tsx
  Composer/packages/client/src/pages/design/PropertyEditor.tsx
  Composer/packages/client/src/pages/design/PropertyEditorHeader.tsx
  Composer/packages/client/src/pages/design/VisualEditor.tsx
  Composer/packages/client/src/pages/design/__tests__/PropertyEditorHeader.test.tsx
  Composer/packages/client/src/pages/design/creationModal.tsx
  Composer/packages/client/src/pages/home/Home.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/atoms/botState.ts
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/dialog.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/project.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/trigger.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/application.ts
  Composer/packages/client/src/recoilModel/dispatchers/dialogs.ts
  Composer/packages/client/src/recoilModel/dispatchers/index.ts
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/recoilModel/dispatchers/trigger.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/packages/client/src/recoilModel/selectors/skills.ts
  Composer/packages/client/src/shell/triggerApi.ts
  Composer/packages/client/src/utils/navigation.ts
  Composer/packages/lib/indexers/__tests__/botIndexer.test.ts
  Composer/packages/lib/indexers/src/botIndexer.ts
  Composer/packages/lib/indexers/src/index.ts
Labels: BotProjects, Not Targetting Main

#4456 feat: Settings page
  Composer/packages/client/__tests__/pages/botProjectsSettings/AppIdAndPassword.test.tsx
  Composer/packages/client/__tests__/pages/botProjectsSettings/BotLanguage.test.tsx
  Composer/packages/client/__tests__/pages/botProjectsSettings/DeleteBotButton.test.tsx
  Composer/packages/client/__tests__/pages/botProjectsSettings/PublishTarget.test.tsx
  Composer/packages/client/__tests__/pages/botProjectsSettings/RootBotExternalService.test.tsx
  Composer/packages/client/__tests__/pages/botProjectsSettings/SkillHostEndPoint.test.tsx
  Composer/packages/client/__tests__/testUtils/renderWithRecoil.tsx
  Composer/packages/client/src/components/BotProjectsSettingsIcon.tsx
  Composer/packages/client/src/components/BotRuntimeController/useBotOperations.ts
  Composer/packages/client/src/components/CollapsableWrapper.tsx
  Composer/packages/client/src/components/Conversation.jsx
  Composer/packages/client/src/components/Header.tsx
  Composer/packages/client/src/components/MultiLanguage/AddLanguageModal.tsx
  Composer/packages/client/src/components/NavItem.tsx
  Composer/packages/client/src/components/Page.tsx
  Composer/packages/client/src/components/TextFieldWithCustomButton.tsx
  Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx
  Composer/packages/client/src/pages/botProject/BotLanguage.tsx
  Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
  Composer/packages/client/src/pages/botProject/BotProjectSettingsTableView.tsx
  Composer/packages/client/src/pages/botProject/DeleteBotButton.tsx
  Composer/packages/client/src/pages/botProject/ExternalService.tsx
  Composer/packages/client/src/pages/botProject/PublishTargets.tsx
  Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
  Composer/packages/client/src/pages/botProject/RuntimeSettings.tsx
  Composer/packages/client/src/pages/botProject/SkillBotExternalService.tsx
  Composer/packages/client/src/pages/botProject/SkillHostEndPoint.tsx
  Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
  Composer/packages/client/src/pages/botProject/runtime-settings/ejectModal.tsx
  Composer/packages/client/src/pages/botProject/runtime-settings/style.ts
  Composer/packages/client/src/pages/botProject/runtime-settings/workingModal.tsx
  Composer/packages/client/src/pages/setting/SettingsPage.tsx
  Composer/packages/client/src/pages/setting/app-settings/AppSettings.tsx
  Composer/packages/client/src/pages/setting/app-settings/SettingDropdown.tsx
  Composer/packages/client/src/pages/setting/app-settings/styles.ts
  Composer/packages/client/src/pages/setting/router.tsx
  Composer/packages/client/src/pages/setting/runtime-settings/style.ts
  Composer/packages/client/src/recoilModel/dispatchers/botProjectFile.ts
  Composer/packages/client/src/recoilModel/dispatchers/multilang.ts
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
  Composer/packages/client/src/recoilModel/dispatchers/setting.ts
  Composer/packages/client/src/recoilModel/dispatchers/skill.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/utils/dialogValidator.ts
  Composer/packages/client/src/utils/pageLinks.ts
  Composer/packages/lib/shared/src/constant.ts
  Composer/packages/lib/ui-shared/src/components/DialogWrapper.tsx
Labels: Not Targetting Main

#4820 fix: export to .zip
  Composer/packages/server/src/models/storage/localDiskStorage.ts
Labels: 1.3

#4795 fix: remove checkURL call from navTo on dialog clicks
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/navigation.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/navigation.ts
Labels: 1.3

#4841 chore: Pull form dialogs feature branch back to main
  Composer/packages/client/src/pages/form-dialog/FormDialogPage.tsx
  Composer/packages/client/src/pages/form-dialog/VisualFormDialogSchemaEditor.tsx
  Composer/packages/client/src/recoilModel/dispatchers/formDialogs.ts
  Composer/packages/client/src/recoilModel/persistence/FilePersistence.ts
  Composer/packages/client/src/recoilModel/persistence/types.ts
  Composer/packages/client/src/utils/pageLinks.ts
  Composer/packages/form-dialogs/src/components/property/FormDialogSchemaDetails.tsx
  Composer/packages/form-dialogs/src/demo/DemoApp.tsx
  Composer/packages/lib/indexers/src/index.ts
  Composer/packages/lib/indexers/src/utils/fileExtensions.ts
  Composer/packages/lib/shared/src/featureFlagUtils/index.ts
  Composer/packages/server/src/locales/en-US.json
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/types/src/indexers.ts
Labels: Area: Form Dialogs

#4743 fix: drag selection mess when zoom in/out
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/AdaptiveFlowEditor.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/components/ZoomZone.tsx
Labels: 1.3

#4295 fix: Disable the default timeout for requests on the LU build
  Composer/packages/server/src/controllers/__tests__/project.test.ts
  Composer/packages/server/src/controllers/project.ts
Labels: 1.3

#4857 chore: Update bf-generate-lib
  Composer/packages/server/package.json
  Composer/yarn.lock
Labels: Area: Form Dialogs

#4801 chore: add missing type declarations in 'useDialogEditApi'
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/AdaptiveFlowEditor.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useDialogEditApi.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useEditorEventApi.ts
Labels: 1.3

#4860 fix: Form dialog fixes requested by UX (melanie)
  Composer/packages/form-dialogs/src/components/property/FormDialogPropertyCard.tsx
  Composer/packages/form-dialogs/src/components/tags/TagInput.tsx
  Composer/packages/form-dialogs/src/components/tags/utils.ts
Labels: Area: Form Dialogs

#4739 fix: Change remote template to use preview package in public feed
  extensions/samples/src/index.ts
Labels: 1.3

#4827 chore: update the navigation link for setting page
  Composer/cypress/integration/LuisDeploy.spec.ts
  Composer/cypress/integration/NotificationPage.spec.ts
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/ProjectTree/treeItem.tsx
  Composer/packages/client/src/pages/diagnostics/Diagnostics.tsx
  Composer/packages/client/src/pages/diagnostics/types.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/recoilModel/selectors/diagnosticsPageSelector.ts
  Composer/packages/client/src/recoilModel/selectors/index.ts
  Composer/packages/client/src/utils/navigation.ts
  Composer/packages/client/src/utils/pageLinks.ts
Labels: Not Targetting Main

#4522 doc: Add CI and CD operation doc for composer language models
  docs/archived docs/how-to-process-language-models-with-CI-CD.md
Labels: 1.3

#4544 fix: change runtime path to relative when ejecting runtime
  Composer/packages/server/src/locales/en-US.json
  extensions/azurePublish/src/index.ts
  extensions/localPublish/src/index.ts
  extensions/runtimes/src/index.ts
Labels: 1.3

#4906 chore: Update the URL of the component feed
  extensions/packageManager/src/node/index.ts
Labels: 1.3

#4913 fix: fixes form dialog generation on electron
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/electron-server/scripts/copy-artifacts.js
Labels: Area: Form Dialogs

#4893 feat: Enable add a knowledge base to a skill in context menu.
  Composer/packages/client/__tests__/pages/knowledge-base/QnAPage.test.tsx
  Composer/packages/client/src/components/Page.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/components/QnA/CreateQnAFrom.tsx
  Composer/packages/client/src/components/QnA/CreateQnAFromUrlModal.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/pages/knowledge-base/QnAPage.tsx
  Composer/packages/client/src/pages/knowledge-base/code-editor.tsx
  Composer/packages/client/src/pages/knowledge-base/table-view.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/dispatchers/qna.ts
Labels: 1.3, Area: Bot project, BotProjects, Not Targetting Main

#4562 feat: sync skillbot's locale with root bot
  Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
  Composer/packages/client/src/pages/botProject/BotProjectSettingsTableView.tsx
  Composer/packages/client/src/recoilModel/dispatchers/multilang.ts
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/utils/pageLinks.ts
Labels: Not Targetting Main

#4924 fix: get history always return empty array
  Composer/packages/server/src/controllers/publisher.ts
  extensions/pvaPublish/src/node/index.ts
Labels: Approved to merge

#4909 chore: Move "recently used" list into the server storage
  extensions/packageManager/src/client/Library.tsx
  extensions/packageManager/src/node/index.ts
Labels: 1.3

#4867 feat: Orchestrator Recognizer Preview
  Composer/packages/adaptive-form/src/components/fields/RecognizerField/RecognizerField.tsx
  Composer/packages/adaptive-form/src/components/fields/RecognizerField/getDropdownOptions.ts
  Composer/packages/client/package.json
  Composer/packages/client/src/components/ComposerFeature.tsx
  Composer/packages/client/src/components/TestController/TestController.tsx
  Composer/packages/client/src/components/TestController/publishDialog.tsx
  Composer/packages/client/src/pages/setting/app-settings/FeatureFlagCheckBox.tsx
  Composer/packages/client/src/pages/setting/app-settings/PreviewFeatureToggle.tsx
  Composer/packages/client/src/plugins.ts
  Composer/packages/client/src/recoilModel/Recognizers.tsx
  Composer/packages/client/src/recoilModel/atoms/botState.ts
  Composer/packages/client/src/recoilModel/dispatchers/recognizers.ts
  Composer/packages/client/src/recoilModel/dispatchers/storage.ts
  Composer/packages/client/src/recoilModel/selectors/validatedDialogs.ts
  Composer/packages/client/src/shell/useShell.ts
  Composer/packages/client/src/utils/buildUtil.ts
  Composer/packages/client/src/utils/dialogUtil.ts
  Composer/packages/client/src/utils/hooks.ts
  Composer/packages/client/src/utils/luUtil.ts
  Composer/packages/electron-server/electron-builder-config.json
  Composer/packages/extension-client/src/hooks/useRecognizerConfig.ts
  Composer/packages/extension-client/src/types/formSchema.ts
  Composer/packages/lib/indexers/src/dialogIndexer.ts
  Composer/packages/lib/shared/src/featureFlagUtils/index.ts
  Composer/packages/server/jest.config.js
  Composer/packages/server/package.json
  Composer/packages/server/src/models/bot/__mocks__/mockLUInput.json
  Composer/packages/server/src/models/bot/__tests__/orchestratorBuilder.test.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/models/bot/builder.ts
  Composer/packages/server/src/models/bot/interface.ts
  Composer/packages/server/src/services/featureFlags.ts
  Composer/packages/types/src/featureFlags.ts
  Composer/packages/types/src/index.ts
  Composer/packages/types/src/indexers.ts
  Composer/packages/types/src/schema.ts
  Composer/packages/types/src/shell.ts
  Composer/packages/ui-plugins/cross-trained/src/index.ts
  Composer/packages/ui-plugins/orchestrator/.eslintrc.js
  Composer/packages/ui-plugins/orchestrator/.gitignore
  Composer/packages/ui-plugins/orchestrator/jest.config.js
  Composer/packages/ui-plugins/orchestrator/package.json
  Composer/packages/ui-plugins/orchestrator/src/index.ts
  Composer/packages/ui-plugins/orchestrator/tsconfig.build.json
  Composer/packages/ui-plugins/orchestrator/tsconfig.json
  Composer/yarn.lock
  Dockerfile
  docs/internal/FeatureFlags.md
  runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
  runtime/dotnet/azurewebapp/Startup.cs
  runtime/dotnet/core/ComposerSettingsExtensions.cs
Labels: 1.3, Approved to merge, Area: Orchestrator

#4925 fix: Add recognizers for form dialog
  Composer/packages/client/src/recoilModel/Recognizers.tsx
Labels: Approved to merge

#4927 chore: cherry pick get history always return empty array
  Composer/packages/server/src/controllers/publisher.ts
  extensions/pvaPublish/src/node/index.ts
Labels: Approved to merge

#4930 fix: Toggle interaction on start bots
  Composer/cypress/integration/LeftNavBar.spec.ts
  Composer/cypress/integration/LuisDeploy.spec.ts
  Composer/cypress/integration/Onboarding.spec.ts
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotControllerMenu.tsx
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/utils/hooks.ts
  Composer/packages/client/src/utils/pageLinks.ts
  Composer/packages/server/src/controllers/__tests__/settings.test.ts
Labels: 1.3, BotProjects, Team: Authoring

#4916 fix: Add diagnostics header on the design page
  Composer/packages/client/src/components/DiagnosticsHeader.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/pages/diagnostics/Diagnostics.tsx
  Composer/packages/client/src/utils/navigation.ts
Labels: BotProjects, Not Targetting Main

#4866 fix: botprojects context menu issues
  Composer/packages/client/src/components/Modal/DisplayManifestModal.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/components/ProjectTree/treeItem.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/packages/client/src/recoilModel/selectors/skills.ts
  Composer/packages/client/src/utils/navigation.ts
  Composer/packages/lib/indexers/__tests__/botIndexer.test.ts
  Composer/packages/lib/indexers/src/botIndexer.ts
  Composer/packages/lib/indexers/src/dialogIndexer.ts
  Composer/packages/lib/indexers/src/index.ts
Labels: 1.3, Area: Bot project, BotProjects, Not Targetting Main

#4934 fix: Dialog creation, trigger creation error resolved
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/recoilModel/dispatchers/multilang.ts
  Composer/packages/client/src/shell/useShell.ts
Labels: 1.3, BotProjects

#4938 fix: make copy, move and paste work for one bot instead of cross bots
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/editor.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/editor.ts
  Composer/packages/client/src/shell/useShell.ts
Labels: Not Targetting Main

#4941 fix: the board in project tree on the ellipsis is taller
  Composer/packages/client/src/components/ProjectTree/ExpandableNode.tsx
  Composer/packages/client/src/components/ProjectTree/treeItem.tsx
Labels: Not Targetting Main

#4877 feat: publish page
  Composer/cypress/integration/Publish.spec.ts
  Composer/packages/client/__tests__/pages/publish/Publish.test.tsx
  Composer/packages/client/src/pages/publish/BotStatusList.tsx
  Composer/packages/client/src/pages/publish/Notifications.tsx
  Composer/packages/client/src/pages/publish/Publish.tsx
  Composer/packages/client/src/pages/publish/PublishDialog.tsx
  Composer/packages/client/src/pages/publish/PublishStatusList.tsx
  Composer/packages/client/src/pages/publish/publishDialog.tsx
  Composer/packages/client/src/pages/publish/styles.ts
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/packages/server/src/locales/en-US.json
Labels: 1.3, BotProjects

#4969 fix: Allows "view dialog" from form dialog schema page
  Composer/packages/client/src/pages/form-dialog/FormDialogPage.tsx
  Composer/packages/client/src/recoilModel/dispatchers/formDialogs.ts
  Composer/packages/server/package.json
  Composer/yarn.lock
Labels: Area: Form Dialogs

#4356 feat: Customized functions in runtime should pass validation and be allowed to start bot
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/setting.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/dialogs.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/recoilModel/selectors/validatedDialogs.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/index.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/types.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/validation.ts
  Composer/packages/lib/indexers/src/validations/index.ts
  Composer/packages/server/src/models/settings/defaultSettingManager.ts
  Composer/packages/types/src/settings.ts
Labels: 1.3

#4979 fix: click show skill manifest no response in form editor
  Composer/packages/client/src/components/Modal/DisplayManifestModal.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/atoms/botState.ts
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/skill.test.ts
  Composer/packages/client/src/recoilModel/dispatchers/skill.ts
  Composer/packages/client/src/recoilModel/selectors/skills.ts
  Composer/packages/client/src/shell/useShell.ts
Labels: 1.3

#4990 chore: remove Add toolbar dropdown button
  Composer/cypress/integration/NewDialog.spec.ts
  Composer/cypress/integration/TriggerCreation.spec.ts
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
Labels: 1.3, Area: Bot project, BotProjects

#5001 fix: skill bot path bug
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/utils/fileUtil.ts
Labels: 1.3, Area: Bot project, BotProjects, Multi-bot management

#4542 chore: add `onOpenDialog` api to support dialog jump
  Composer/packages/adaptive-flow/__tests__/adaptive-flow-editor/stubs/ShellApiStub.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useEditorEventApi.ts
  Composer/packages/client/src/shell/useShell.ts
  Composer/packages/types/src/shell.ts
Labels: 1.3

#4991 fix: a11y in all-up view
  Composer/packages/client/src/components/EditableField.tsx
Labels: Approved to merge

#4521 fix: check if port in use before showing success message on local publishing
  extensions/azurePublish/yarn.lock
  extensions/localPublish/package.json
  extensions/localPublish/src/index.ts
  extensions/localPublish/yarn.lock
Labels: 1.3
