Repository microsoft/BotFramework-Composer, pull requests merged in 2020-02, with the labels that each got.

#1889 fix: LU LSP suggest empty string entities and roles in entering utterance
  Composer/packages/tools/language-servers/language-understanding/src/matchingPattern.ts
Labels: Approved to merge

#1856 feat: click on a inline lg template error it will navigate to design page and focus on the specific action
  Composer/packages/client/src/pages/language-generation/table-view.tsx
  Composer/packages/client/src/pages/notifications/index.tsx
  Composer/packages/client/src/pages/notifications/useNotifications.tsx
  Composer/packages/client/src/utils/navigation.ts
  Composer/packages/lib/indexers/src/dialogIndexer.ts
  Composer/packages/lib/indexers/src/type.ts
  Composer/packages/lib/indexers/src/utils/index.ts
  Composer/packages/lib/shared/src/lgUtils/index.ts
  Composer/packages/server/__tests__/models/bot/botProject.test.ts
Labels: Approved to merge

#1988 refactor: update the validation for new schema
  Composer/packages/lib/indexers/src/dialogUtils/dialogChecker.ts
  Composer/packages/lib/indexers/src/dialogUtils/validation.ts
Labels: Not Target Master

#1939 fix: update framework and package version in template botproject
  BotProject/Templates/CSharp/BotProject.csproj
  BotProject/Templates/CSharp/Program.cs
  BotProject/Templates/CSharp/Schemas/sdk.schema
  BotProject/Templates/CSharp/Scripts/build_runtime.ps1
  BotProject/Templates/CSharp/Scripts/build_runtime.sh
  BotProject/Templates/CSharp/Startup.cs
  BotProject/Templates/CSharp/Tests/Tests.csproj
  Composer/Dockerfile
  Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/PromptSettings.tsx
  Composer/packages/extensions/obiformeditor/src/Form/widgets/TextWidget.tsx
  Composer/packages/lib/indexers/src/dialogUtils/dialogChecker.ts
  Composer/packages/lib/indexers/src/dialogUtils/validation.ts
  Composer/packages/lib/shared/__tests__/dialogFactory.test.ts
  Composer/packages/lib/shared/src/appschema.ts
  Composer/packages/server/schemas/sdk.schema
  Composer/packages/server/src/models/connector/csharpBotConnector.ts
  Composer/packages/server/src/settings/env.ts
  Composer/packages/server/src/settings/index.ts
Labels: Approved to merge

#1932 support BeginSkill in Composer
  Composer/packages/extensions/obiformeditor/src/schema/uischema.ts
  Composer/packages/extensions/visual-designer/src/schema/uischema.tsx
  Composer/packages/lib/shared/src/appschema.ts
  Composer/packages/lib/shared/src/labelMap.ts
  Composer/packages/lib/shared/src/types/schema.ts
  Composer/packages/lib/shared/src/viewUtils.ts
Labels: Not Target Master

#1996 chore: sync new schema in form editor
  Composer/packages/lib/shared/src/appschema.ts
Labels: Approved to merge

#2045 chore: Replace animated screenshots on "Publish" page with static ones
  Composer/packages/client/src/pages/setting/deployment/deploy-create-output.png
  Composer/packages/client/src/pages/setting/deployment/deploy-deploy-output.png
  Composer/packages/client/src/pages/setting/deployment/deployWizardStep-getCreate.js
  Composer/packages/client/src/pages/setting/deployment/deployWizardStep-getDeploy.js
Labels: R8

#1994 feat: support inline LU section editing
  Composer/packages/client/src/pages/language-generation/code-editor.tsx
  Composer/packages/client/src/pages/language-generation/index.tsx
  Composer/packages/client/src/pages/language-understanding/code-editor.js
  Composer/packages/client/src/pages/language-understanding/code-editor.tsx
  Composer/packages/client/src/pages/language-understanding/index.tsx
  Composer/packages/client/src/pages/language-understanding/table-view.tsx
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/store/action/lu.ts
  Composer/packages/client/src/store/reducer/index.ts
  Composer/packages/client/src/utils/luUtil.ts
  Composer/packages/lib/code-editor/demo/src/index.tsx
  Composer/packages/lib/code-editor/demo/src/luEditor.tsx
  Composer/packages/lib/code-editor/demo/src/luInlineEditor.tsx
  Composer/packages/lib/code-editor/src/LuEditor.tsx
  Composer/packages/lib/code-editor/src/languages/lu.ts
  Composer/packages/lib/indexers/__tests__/luIndexer.test.ts
  Composer/packages/lib/indexers/__tests__/luUtil.test.ts
  Composer/packages/lib/indexers/src/luIndexer.ts
  Composer/packages/lib/indexers/src/type.ts
  Composer/packages/lib/indexers/src/types/bf-lu.d.ts
  Composer/packages/lib/indexers/src/utils/diagnosticUtil.ts
  Composer/packages/lib/indexers/src/utils/luUtil.ts
  Composer/packages/server/assets/projects/ToDoBotWithLuisSample/ComposerDialogs/Main/Main.lg
  Composer/packages/server/assets/projects/ToDoBotWithLuisSample/ComposerDialogs/Main/Main.lu
  Composer/packages/server/src/server.ts
  Composer/packages/server/src/services/project.ts
  Composer/packages/tools/language-servers/language-understanding/package.json
  Composer/packages/tools/language-servers/language-understanding/src/LUServer.ts
  Composer/packages/tools/language-servers/language-understanding/src/utils.ts
  Composer/yarn.lock
Labels: Approved to merge

#2065 chore: fix hover state nodes ui
  Composer/packages/extensions/visual-designer/src/components/renderers/ElementWrapper.tsx
Labels: Approved to merge

#2096 chore: remove 'InitProperty' type in Composer
  Composer/packages/extensions/obiformeditor/demo/src/editorschema.json
  Composer/packages/extensions/visual-designer/demo/src/samples/todo/AddToDo.json
  Composer/packages/extensions/visual-designer/demo/src/stories/VisualSDKDemo.js
  Composer/packages/extensions/visual-designer/src/schema/uischema.tsx
  Composer/packages/lib/shared/src/appschema.ts
  Composer/packages/lib/shared/src/labelMap.ts
  Composer/packages/lib/shared/src/types/schema.ts
  Composer/packages/lib/shared/src/viewUtils.ts
  Composer/packages/server/schemas/editor.schema
Labels: Not Target Master

#2097 chore: update lg template pattern
  Composer/packages/lib/shared/src/lgUtils/parsers/lgPatterns.ts
Labels: Not Target Master
