Repository microsoft/BotFramework-Composer, pull requests merged in 2020-09, with the labels that each got.

#3977 doc: update 1.1.0.md
  releases/1.1.0.md
Labels: Ready

#4063 doc: update title of "new bot" dialog
  Composer/packages/client/src/components/CreationFlow/DefineConversation.tsx
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/pages/design/createDialogModal.tsx
Labels: Approved to merge

#4071 fix: check whether it is a bot project folder while opening
  Composer/packages/server/src/services/project.ts
  Composer/packages/server/src/services/storage.ts
Labels: Approved to merge

#4133 fix: security: downgrade node-forge to 0.9.0
  Composer/package.json
  Composer/yarn.lock
Labels: Needs review

#3986 build: fix docker builds in ACR
  Composer/.dockerignore
  Composer/Dockerfile
Labels: Approved to merge

#4112 fix: checkReturnType in ExpressionValidation throws unexpected error
  Composer/cypress/integration/NotificationPage.spec.ts
  Composer/packages/lib/indexers/__tests__/validations/expressionValidation.test.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/types.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/utils.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/validation.ts
Labels: Approved to merge

#4110 fix: defense the usage of 'match()' method in skillsUtils
  Composer/packages/lib/shared/src/skillsUtils/index.ts
Labels: Approved to merge

#4138 fix: sync locale files and add missing "example" string
  Composer/packages/adaptive-form/src/utils/uiOptionsHelpers.ts
  Composer/packages/server/src/locales/en-US.json
Labels: Approved to merge

#4078 fix: check whether operation is under current project folder
  Composer/packages/server/__tests__/controllers/project.test.ts
  Composer/packages/server/src/models/bot/botProject.ts
Labels: Approved to merge

#3985 feat: Add QnA files to dispatch model in skill manifest
  Composer/packages/client/src/pages/design/exportSkillModal/__tests__/generateSkillManifest.test.ts
  Composer/packages/client/src/pages/design/exportSkillModal/generateSkillManifest.ts
  Composer/packages/client/src/pages/design/exportSkillModal/index.tsx
Labels: Approved to merge

#3980 feat: add directline extensions support by default, for webapp runtime only
  runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
  runtime/dotnet/azurewebapp/Startup.cs
Labels: Approved to merge

#4129 fix: Removing browser autocomplete on Intellisense fields
  Composer/packages/adaptive-form/src/components/fields/ExpressionField/ExpressionEditor.tsx
  Composer/packages/adaptive-form/src/components/fields/IntellisenseField.tsx
Labels: Approved to merge

#4155 fix: language err for build luis in azure deploy
  Composer/plugins/azurePublish/src/deploy.ts
  Composer/plugins/azurePublish/src/index.ts
Labels: Approved to merge

#4231 feat: Added fieldSets to UIOptions
  Composer/packages/adaptive-form/src/components/CollapseField.tsx
  Composer/packages/adaptive-form/src/components/fields/FieldSets.tsx
  Composer/packages/adaptive-form/src/components/fields/__tests__/FieldSets.test.tsx
  Composer/packages/adaptive-form/src/components/fields/index.ts
  Composer/packages/adaptive-form/src/utils/__tests__/getFieldSets.test.ts
  Composer/packages/adaptive-form/src/utils/getFieldSets.ts
  Composer/packages/adaptive-form/src/utils/index.ts
  Composer/packages/adaptive-form/src/utils/resolveFieldWidget.ts
  Composer/packages/extension-client/src/types/formSchema.ts
  Composer/packages/ui-plugins/schema-editor/src/Fields/CollapsedField.tsx
  Composer/packages/ui-plugins/schema-editor/src/uiOptions.ts
Labels: Approved to merge

#4135 feat: UI Schema - Recognizer
  Composer/packages/adaptive-form/jest.config.js
  Composer/packages/adaptive-form/src/components/FormTitle.tsx
  Composer/packages/adaptive-form/src/components/fields/CustomRecognizerField.tsx
  Composer/packages/adaptive-form/src/components/fields/IntentField.tsx
  Composer/packages/adaptive-form/src/components/fields/RecognizerField.tsx
  Composer/packages/adaptive-form/src/components/fields/RecognizerField/RecognizerField.tsx
  Composer/packages/adaptive-form/src/components/fields/RecognizerField/defaultRecognizerOrder.ts
  Composer/packages/adaptive-form/src/components/fields/RecognizerField/getDropdownOptions.ts
  Composer/packages/adaptive-form/src/components/fields/RecognizerField/index.ts
  Composer/packages/adaptive-form/src/components/fields/RecognizerField/mappers.ts
  Composer/packages/adaptive-form/src/components/fields/RecognizerField/useMigrationEffect.ts
  Composer/packages/adaptive-form/src/components/fields/__tests__/IntentField.test.tsx
  Composer/packages/adaptive-form/src/components/fields/__tests__/RecognizerField.test.tsx
  Composer/packages/adaptive-form/src/components/fields/index.ts
  Composer/packages/adaptive-form/src/defaultRecognizers.ts
  Composer/packages/client/__tests__/plugins.test.ts
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/pages/design/createDialogModal.tsx
  Composer/packages/client/src/plugins.ts
  Composer/packages/client/src/utils/dialogUtil.ts
  Composer/packages/extension-client/src/hooks/__tests__/useRecognizerConfig.test.tsx
  Composer/packages/extension-client/src/hooks/useRecognizerConfig.ts
  Composer/packages/extension-client/src/types/extension.ts
  Composer/packages/extension-client/src/types/formSchema.ts
  Composer/packages/extension-client/src/types/index.ts
  Composer/packages/extension-client/src/types/recognizerSchema.ts
  Composer/packages/extension-client/src/utils/__tests__/mergePluginConfigs.test.ts
  Composer/packages/extension-client/src/utils/mergePluginConfigs.ts
  Composer/packages/lib/shared/src/types/sdk.ts
  Composer/packages/ui-plugins/composer/src/defaultRecognizerSchema.ts
  Composer/packages/ui-plugins/composer/src/index.ts
  Composer/packages/ui-plugins/cross-trained/src/index.ts
  Composer/packages/ui-plugins/luis/src/index.ts
  Composer/packages/ui-plugins/prompts/src/PromptField/UserInput.tsx
Labels: Area: PVA, Needs review

#4212 fix: provision issue for QnA, split QnA template
  Composer/plugins/samples/assets/shared/scripts/DeploymentTemplates/qna-template.json
  Composer/plugins/samples/assets/shared/scripts/DeploymentTemplates/template-with-preexisting-rg.json
  Composer/plugins/samples/assets/shared/scripts/provisionComposer.js
Labels: Approved to merge

#4153 chore: extract build logic from components page
  Composer/packages/client/__tests__/utils/buildUtil.test.ts
  Composer/packages/client/__tests__/utils/luUtil.test.ts
  Composer/packages/client/src/components/TestController/TestController.tsx
  Composer/packages/client/src/recoilModel/dispatchers/builder.ts
  Composer/packages/client/src/utils/buildUtil.ts
  Composer/packages/client/src/utils/luUtil.ts
Labels: Area: Quality

#4126 fix: Object examples not properly displayed as placeholders
  Composer/packages/adaptive-form/src/utils/__tests__/uiOptionsHelpers.test.ts
  Composer/packages/adaptive-form/src/utils/uiOptionsHelpers.ts
Labels: Approved to merge

#4080 feat: add notification center for composer (QnA url import)
  Composer/packages/client/src/components/AppComponents/MainContainer.tsx
  Composer/packages/client/src/components/NotificationCard.tsx
  Composer/packages/client/src/components/NotificationContainer.tsx
  Composer/packages/client/src/components/__tests__/NotificationCard.test.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/dispatchers/index.ts
  Composer/packages/client/src/recoilModel/dispatchers/notification.ts
  Composer/packages/client/src/recoilModel/dispatchers/qna.ts
  Composer/packages/client/src/recoilModel/selectors/notificationsSelector.ts
  Composer/packages/client/src/recoilModel/types.ts
  Composer/packages/client/src/utils/notifications.ts
  Composer/packages/client/src/utils/timer.ts
Labels: Approved to merge

#4082 fix: do not create duplicated qnamatcher trigger
  Composer/packages/client/src/pages/design/DesignPage.tsx
Labels: Needs review

#3858 feat: use uischema to define Flow Actions
  Composer/packages/adaptive-flow/__tests__/adaptive-flow-renderer/utils/widgetExpressionEvaluator.test.ts
  Composer/packages/adaptive-flow/__tests__/adaptive-flow-renderer/utils/widgetRenderer.test.tsx
  Composer/packages/adaptive-flow/package.json
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/AdaptiveFlowEditor.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/adaptive/AdaptiveDialog.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/configs/builtinSchema.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/configs/builtinSchema.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/configs/builtinWidgets.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/types/flowRenderer.types.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/utils/expression/widgetExpressionEvaluator.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/utils/visual/WidgetSchemaProvider.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/utils/visual/widgetRenderer.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/ActionCard/ActionCard.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/ActionHeader/ActionHeader.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/DialogRef.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/ForeachWidget.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/IfConditionWidget.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/PromptWidget.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/PropertyDescription.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/ResourceOperation.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/SwitchConditionWidget.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/index.ts
  Composer/packages/extension-client/src/types/extension.ts
  Composer/packages/extension-client/src/types/flowSchema.ts
  Composer/packages/lib/ui-shared/src/components/ListOverview.tsx
  Composer/packages/ui-plugins/composer/src/defaultFlowSchema.ts
  Composer/packages/ui-plugins/composer/src/index.ts
  Composer/packages/ui-plugins/prompts/src/index.tsx
Labels: Needs review, R11

#4240 feat: Adds support for additional fields in UIOptions
  Composer/packages/adaptive-form/src/components/FormRow.tsx
  Composer/packages/adaptive-form/src/components/__tests__/FormRow.test.tsx
  Composer/packages/adaptive-form/src/components/fields/FieldSets.tsx
  Composer/packages/adaptive-form/src/components/fields/ObjectField.tsx
  Composer/packages/adaptive-form/src/components/fields/__tests__/FieldSets.test.tsx
  Composer/packages/adaptive-form/src/components/fields/__tests__/ObjectField.test.tsx
  Composer/packages/adaptive-form/src/utils/__tests__/getFieldSets.test.ts
  Composer/packages/adaptive-form/src/utils/__tests__/getSchemaWithAdditionalFields.test.ts
  Composer/packages/adaptive-form/src/utils/getFieldSets.ts
  Composer/packages/adaptive-form/src/utils/getFieldsets.ts
  Composer/packages/adaptive-form/src/utils/getSchemaWithAdditionalFields.ts
  Composer/packages/adaptive-form/src/utils/index.ts
  Composer/packages/adaptive-form/src/utils/resolveFieldWidget.ts
  Composer/packages/extension-client/src/types/formSchema.ts
  Composer/packages/server/src/controllers/__tests__/project.test.ts
  Composer/packages/ui-plugins/composer/src/index.ts
  Composer/packages/ui-plugins/schema-editor/src/Fields/AdaptiveDialogField.tsx
  Composer/packages/ui-plugins/schema-editor/src/Fields/SchemaEditorField.tsx
  Composer/packages/ui-plugins/schema-editor/src/formSchema.ts
  Composer/packages/ui-plugins/schema-editor/src/uiOptions.ts
  Composer/packages/ui-plugins/select-skill-dialog/src/BeginSkillDialogField.tsx
  Composer/packages/ui-plugins/select-skill-dialog/src/SelectSkillDialogField.tsx
  Composer/packages/ui-plugins/select-skill-dialog/src/SkillEndpointField.tsx
  Composer/packages/ui-plugins/select-skill-dialog/src/__tests__/SelectSkillDialog.test.tsx
  Composer/packages/ui-plugins/select-skill-dialog/src/__tests__/SkillEndpointField.test.tsx
  Composer/packages/ui-plugins/select-skill-dialog/src/index.ts
Labels: Team: Authoring

#4292 feat: Included en-US schemas for localization
  Composer/.gitignore
  Composer/packages/server/.gitignore
  Composer/packages/server/schemas/sdk.en-US.schema
  Composer/packages/server/schemas/sdk.en-US.uischema
  Composer/packages/server/src/locales/en-US.json
Labels: Team: Authoring

#4264 feat: add extensions page in settings
  Composer/packages/client/src/components/PluginHost/PluginHost.tsx
  Composer/packages/client/src/pages/setting/SettingsPage.tsx
  Composer/packages/client/src/pages/setting/extensions/ExtensionSearchResults.tsx
  Composer/packages/client/src/pages/setting/extensions/Extensions.tsx
  Composer/packages/client/src/pages/setting/extensions/InstallExtensionDialog.tsx
  Composer/packages/client/src/pages/setting/router.tsx
  Composer/packages/client/src/recoilModel/dispatchers/extensions.ts
  Composer/packages/client/src/recoilModel/types.ts
  Composer/packages/client/src/utils/hooks.ts
  Composer/packages/client/src/utils/pageLinks.ts
  Composer/packages/extension/src/manager/manager.ts
  Composer/packages/extension/src/types/extension.ts
  Composer/packages/extension/src/utils/npm.ts
  Composer/packages/server/src/controllers/__tests__/extensions.test.ts
  Composer/packages/server/src/controllers/extensions.ts
  Composer/plugins/sample-ui-plugin/README.md
  Composer/plugins/sample-ui-plugin/package.json
Labels: Team: Platform

#4298 fix: Typing too fast in composer results in dropped characters
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useSelectionEffect.ts
Labels: Team: Platform

#4242 feat: $designer.id based URL
  Composer/packages/client/__tests__/utils/convertUtils/designerPathEncoder.test.ts
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/recoilModel/dispatchers/navigation.ts
  Composer/packages/client/src/utils/convertUtils/designerPathEncoder.ts
  Composer/packages/client/src/utils/convertUtils/parsePathToSelected.ts
Labels: Team: Platform
