Repository microsoft/BotFramework-Composer, pull requests merged in 2020-08, with the labels that each got.

#3784 fix: use different shellData in Form and Flow's ExtensionContext
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/shell/useShell.ts
  Composer/packages/extensions/extension/src/components/Extension.tsx
  Composer/packages/lib/shared/src/types/shell.ts
  Composer/packages/ui-plugins/select-dialog/src/__tests__/selectDialog.test.tsx
  Composer/packages/ui-plugins/select-skill-dialog/src/__tests__/BeginSkillDialogField.test.tsx
  Composer/packages/ui-plugins/select-skill-dialog/src/__tests__/SelectSkillDialog.test.tsx
Labels: Approved to merge

#3763 fix: Remove the logic of forcing the autoEndDialog to be false
  runtime/dotnet/core/ComposerBot.cs
Labels: Approved to merge

#3852 fix: refresh page client state lost error.
  Composer/cypress/support/index.ts
  Composer/packages/client/src/components/CreationFlow/CreationFlow.tsx
  Composer/packages/client/src/pages/home/Home.tsx
  Composer/packages/client/src/pages/setting/SettingsPage.tsx
  Composer/packages/client/src/pages/setting/dialog-settings/DialogSettings.tsx
  Composer/packages/client/src/pages/setting/runtime-settings/RuntimeSettings.tsx
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/utils/hooks.ts
  Composer/packages/client/src/utils/projectCache.ts
Labels: Approved to merge, R10-RC

#3847 fix: multi-lang all up view refinement
  Composer/packages/client/src/components/EditableField.tsx
  Composer/packages/client/src/components/MultiLanguage/AddLanguageModal.tsx
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/pages/language-generation/table-view.tsx
  Composer/packages/client/src/pages/language-understanding/table-view.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/dialog.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/lu.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/lg.ts
  Composer/packages/client/src/recoilModel/dispatchers/lu.ts
  Composer/packages/lib/indexers/src/utils/luUtil.ts
Labels: Needs review, R10-RC

#3857 separated QnAEditor & rename to knowledge-base
  Composer/packages/client/src/components/CreationFlow/CreationFlow.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/pages/knowledge-base/ImportQnAFromUrlModal.tsx
  Composer/packages/client/src/pages/knowledge-base/QnAPage.tsx
  Composer/packages/client/src/pages/knowledge-base/code-editor.tsx
  Composer/packages/client/src/pages/knowledge-base/styles.ts
  Composer/packages/client/src/pages/knowledge-base/table-view.tsx
  Composer/packages/client/src/pages/notifications/Notifications.tsx
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/recoilModel/dispatchers/qna.ts
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/utils/pageLinks.ts
  Composer/packages/extensions/adaptive-form/src/components/fields/QnAActionsField.tsx
  Composer/packages/lib/code-editor/src/QnAEditor.tsx
  Composer/packages/lib/code-editor/src/index.ts
  Composer/packages/server/src/controllers/utilities.ts
  Composer/packages/server/src/models/utilities/parser.ts
  Composer/packages/server/src/router/api.ts
Labels: Not Target Master

#3859 qna-recognizer add tests
  Composer/packages/client/__tests__/components/triggerCreationModal.test.tsx
  Composer/packages/client/__tests__/shell/triggerApi.test.tsx
Labels: Not Target Master

#3871 fix: open a new bot will navigate to the old bot
  Composer/packages/client/src/pages/design/DesignPage.tsx
Labels: Approved to merge, R10-RC

#3870 fix: AskingQuestionsSample sample bot
  Composer/plugins/samples/assets/projects/AskingQuestionsSample/askingquestionssample.dialog
  Composer/plugins/samples/assets/projects/AskingQuestionsSample/language-generation/en-us/askingquestionssample.en-us.lg
Labels: Approved to merge, R10-RC

#3868 fix: lg tablelist bugfix & regressions
  Composer/packages/client/src/pages/language-generation/table-view.tsx
  Composer/packages/client/src/recoilModel/dispatchers/lu.ts
  Composer/packages/lib/indexers/__tests__/lgUtil.test.ts
  Composer/packages/lib/indexers/__tests__/luUtil.test.ts
  Composer/packages/lib/indexers/__tests__/utils/diagnosticUtil.test.ts
  Composer/packages/lib/indexers/src/utils/lgUtil.ts
  Composer/packages/lib/indexers/src/utils/luUtil.ts
Labels: R10-RC

#3883 fix: clean the cache when deleting a bot
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/utils/projectCache.ts
Labels: Approved to merge

#3885 fix: do not allow editing of publish profile name
  Composer/packages/client/src/pages/publish/createPublishTarget.tsx
  Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
Labels: Approved to merge
