Repository microsoft/BotFramework-Composer, pull requests merged in 2020-03, with the labels that each got.

#2136 feat: implement new action design to improve readability
  Composer/packages/extensions/visual-designer/__tests__/components/nodes/FormCard.test.tsx
  Composer/packages/extensions/visual-designer/demo/src/stories/VisualSDKDemo.js
  Composer/packages/extensions/visual-designer/src/components/common/ListOverview.tsx
  Composer/packages/extensions/visual-designer/src/components/elements/sharedCSS.tsx
  Composer/packages/extensions/visual-designer/src/components/elements/styledComponents.tsx
  Composer/packages/extensions/visual-designer/src/components/elements/styledComponents.types.ts
  Composer/packages/extensions/visual-designer/src/components/lib/ArrowLine.tsx
  Composer/packages/extensions/visual-designer/src/components/menus/IconMenu.tsx
  Composer/packages/extensions/visual-designer/src/components/nodes/templates/CardTemplate.tsx
  Composer/packages/extensions/visual-designer/src/components/nodes/templates/FormCard.tsx
  Composer/packages/extensions/visual-designer/src/constants/ElementSizes.ts
  Composer/packages/extensions/visual-designer/src/schema/uischema.tsx
  Composer/packages/extensions/visual-designer/src/widgets/ActionCard.tsx
  Composer/packages/extensions/visual-designer/src/widgets/ActionHeader.tsx
  Composer/packages/extensions/visual-designer/src/widgets/ActivityRenderer.tsx
  Composer/packages/extensions/visual-designer/src/widgets/DialogRef.tsx
  Composer/packages/extensions/visual-designer/src/widgets/DialogRefCard.tsx
Labels: Needs review

#2069 feat: Add cross train before luis publish
  Composer/packages/client/package.json
  Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/UserInput.tsx
  Composer/packages/extensions/obiformeditor/src/Form/widgets/LuEditorWidget.tsx
  Composer/packages/lib/indexers/package.json
  Composer/packages/lib/indexers/src/dialogIndexer.ts
  Composer/packages/lib/indexers/src/dialogUtils/extractIntentTriggers.ts
  Composer/packages/lib/indexers/src/dialogUtils/types.ts
  Composer/packages/lib/indexers/src/luIndexer.ts
  Composer/packages/lib/indexers/src/type.ts
  Composer/packages/lib/indexers/src/types/bf-lu.d.ts
  Composer/packages/lib/indexers/src/utils/luUtil.ts
  Composer/packages/server/__tests__/models/bot/luisPublisher.test.ts
  Composer/packages/server/package.json
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/models/bot/interface.ts
  Composer/packages/server/src/models/bot/luPublisher.ts
  Composer/packages/server/src/models/storage/interface.ts
  Composer/packages/server/src/models/storage/localDiskStorage.ts
  Composer/packages/server/src/types/bf-lu.d.ts
  Composer/packages/tools/language-servers/language-understanding/package.json
  Composer/yarn.lock
Labels: Needs review

#2217 fix: sort action ids correctly
  Composer/packages/extensions/visual-designer/__tests__/utils/normalizeSelection.test.ts
  Composer/packages/extensions/visual-designer/src/utils/normalizeSelection.ts
Labels: Not Target Master

#2234 fix: make MoveSelection work (not target master)
  Composer/packages/client/src/pages/design/index.tsx
  Composer/packages/extensions/visual-designer/src/editors/ObiEditor.tsx
  Composer/packages/extensions/visual-designer/src/utils/jsonTracker.ts
  Composer/packages/lib/shared/src/dialogFactory.ts
Labels: Not Target Master

#2256 fix: add luis publish status in client
  Composer/packages/client/__tests__/store/reducer/reducer.test.js
  Composer/packages/client/src/pages/language-understanding/table-view.tsx
  Composer/packages/client/src/store/action/dialog.ts
  Composer/packages/client/src/store/action/lu.ts
  Composer/packages/client/src/store/reducer/index.ts
  Composer/packages/client/src/utils/luFileStatusStorage.ts
Labels: Needs review

#2278 fix: ErrorMessage can not be displayed in two expression field.
  Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/twoSettingFields.tsx
Labels: Approved to merge

#2307 fix: Replace Deprecated CosmosDB Interface in BotProject
  BotProject/Templates/CSharp/BotSettings.cs
  BotProject/Templates/CSharp/ComposerBot.cs
  BotProject/Templates/CSharp/DeploymentTemplates/template-with-preexisting-rg.json
  BotProject/Templates/CSharp/Startup.cs
Labels: Approved to merge

#2173 fix: fix SendActivity flikering issue by turning async Lg api call to sync
  Composer/packages/extensions/visual-designer/src/editors/StepEditor.tsx
  Composer/packages/extensions/visual-designer/src/hooks/useLgTemplate.ts
  Composer/packages/extensions/visual-designer/src/hooks/useWindowDimensions.ts
  Composer/packages/extensions/visual-designer/src/index.tsx
  Composer/packages/extensions/visual-designer/src/store/NodeRendererContext.ts
  Composer/packages/extensions/visual-designer/src/utils/hooks.ts
  Composer/packages/extensions/visual-designer/src/widgets/ActivityRenderer.tsx
Labels: R9

#2176 fix: fix Visual Editor nested flow flickering issue by improving layout cache management
  Composer/packages/extensions/visual-designer/__tests__/transformers/jsonTracker.test.ts
  Composer/packages/extensions/visual-designer/src/editors/ObiEditor.tsx
  Composer/packages/extensions/visual-designer/src/store/DesignerCache.ts
  Composer/packages/extensions/visual-designer/src/utils/jsonTracker.ts
Labels: R9

#2208 feat: Rewrite suggestions and diagnostics in LG LSP with latest LG APIs
  Composer/packages/client/package.json
  Composer/packages/client/src/pages/language-generation/code-editor.tsx
  Composer/packages/client/src/pages/notifications/useNotifications.tsx
  Composer/packages/client/src/store/index.tsx
  Composer/packages/client/src/store/reducer/index.ts
  Composer/packages/client/src/utils/dialogUtil.ts
  Composer/packages/client/src/utils/lgUtil.ts
  Composer/packages/extensions/obiformeditor/demo/src/index.tsx
  Composer/packages/extensions/obiformeditor/package.json
  Composer/packages/lib/indexers/__tests__/lgIndexer.test.ts
  Composer/packages/lib/indexers/__tests__/lgUtil.test.ts
  Composer/packages/lib/indexers/package.json
  Composer/packages/lib/indexers/src/dialogUtils/validation.ts
  Composer/packages/lib/indexers/src/lgIndexer.ts
  Composer/packages/lib/indexers/src/utils/lgUtil.ts
  Composer/packages/tools/language-servers/language-generation/__tests__/app.test.ts
  Composer/packages/tools/language-servers/language-generation/package.json
  Composer/packages/tools/language-servers/language-generation/src/LGServer.ts
  Composer/packages/tools/language-servers/language-generation/src/builtinFunctionsMap.ts
  Composer/packages/tools/language-servers/language-generation/src/utils.ts
  Composer/yarn.lock
Labels: Needs review

#2349 fix: Auto search root dialog instead of hard code to main.dialog
  BotProject/Templates/CSharp/ComposerBot.cs
  BotProject/Templates/CSharp/Startup.cs
Labels: P0

#2358 fix: can't find referred lu files for publishing
  Composer/packages/server/src/models/bot/botProject.ts
Labels: Approved to merge

#2274 fix: add disk names
  Composer/packages/client/src/CreationFlow/DefineConversation/index.tsx
  Composer/packages/client/src/CreationFlow/LocationBrowser/FileSelector.tsx
  Composer/packages/client/src/CreationFlow/LocationBrowser/LocationSelectContent.tsx
  Composer/packages/client/src/CreationFlow/OpenProject/index.tsx
  Composer/packages/client/src/CreationFlow/index.js
  Composer/packages/client/src/pages/design/createDialogModal.tsx
  Composer/packages/server/src/services/storage.ts
  Composer/packages/server/src/settings/env.ts
  Composer/packages/server/src/settings/index.ts
  Composer/packages/server/src/store/migrations.ts
Labels: Approved to merge

#2454 docs: update docs in readme to point to docs site
  README.md
Labels: Type: Documentation
