Repository microsoft/BotFramework-Composer, pull requests merged in 2020-04, with the labels that each got.

#2540 fix: editor warning message hidden
  Composer/packages/lib/code-editor/demo/src/baseEditor.tsx
  Composer/packages/lib/code-editor/src/BaseEditor.tsx
Labels: Approved to merge

#2548 fix: There is no need to parse all lu files when updating
  Composer/packages/client/src/store/reducer/index.ts
Labels: Approved to merge

#2542 fix: add locale to lu cross train config
  Composer/packages/client/__tests__/utils/luUtil.test.ts
  Composer/packages/client/src/utils/luUtil.ts
  Composer/packages/server/__tests__/mocks/samplebots/bot1/dialogs/a/a.dialog
Labels: Approved to merge

#2464 fix: Permission issue
  Composer/packages/client/src/CreationFlow/DefineConversation/index.tsx
  Composer/packages/client/src/CreationFlow/LocationBrowser/FileSelector.tsx
  Composer/packages/client/src/CreationFlow/LocationBrowser/LocationSelectContent.tsx
  Composer/packages/client/src/CreationFlow/OpenProject/index.tsx
  Composer/packages/client/src/CreationFlow/index.js
  Composer/packages/server/src/services/storage.ts
Labels: Approved to merge

#2557 fix: catch the throw error message from the luis file check function
  Composer/packages/client/__tests__/components/TestController/emulatorOpenButton.test.tsx
  Composer/packages/client/__tests__/components/TestController/errorCallout.test.tsx
  Composer/packages/client/__tests__/components/TestController/errorInfo.test.tsx
  Composer/packages/client/__tests__/components/TestController/loading.test.tsx
  Composer/packages/client/src/TestController.tsx
  Composer/packages/client/src/components/TestController/emulatorOpenButton.tsx
  Composer/packages/client/src/components/TestController/errorCallout.tsx
  Composer/packages/client/src/components/TestController/errorInfo.tsx
  Composer/packages/client/src/components/TestController/index.tsx
  Composer/packages/client/src/components/TestController/loading.tsx
  Composer/packages/client/src/components/TestController/publishDialog.tsx
  Composer/packages/client/src/components/TestController/styles.ts
  Composer/packages/client/src/constants/index.ts
  Composer/packages/client/src/pages/design/index.tsx
  Composer/packages/client/src/pages/language-generation/index.tsx
  Composer/packages/client/src/pages/language-understanding/index.tsx
  Composer/packages/client/src/pages/setting/index.tsx
  Composer/packages/client/src/pages/skills/index.tsx
  Composer/packages/client/src/store/action/lu.ts
  Composer/packages/client/src/store/action/project.ts
  Composer/packages/client/src/store/action/publisher.ts
  Composer/packages/client/src/store/index.tsx
  Composer/packages/client/src/store/reducer/index.ts
  Composer/packages/client/src/store/types.ts
  Composer/packages/client/src/styles.ts
Labels: Approved to merge

#2681 fix: Auto-Suggestion for fields and values for structure LG
  Composer/packages/lib/code-editor/src/BaseEditor.tsx
  Composer/packages/tools/language-servers/language-generation/src/LGServer.ts
  Composer/packages/tools/language-servers/language-generation/src/utils.ts
Labels: Approved to merge

#2674 [not target master] feat: LU copy api
  Composer/packages/lib/shared/src/types/shell.ts
Labels: Not Target Master

#2714 fix: some UI bugs
  Composer/packages/client/src/CreationFlow/CreateOptions/styles.js
  Composer/packages/client/src/components/ProjectTree/styles.ts
  Composer/packages/client/src/components/ProjectTree/treeItem.tsx
  Composer/packages/client/src/pages/language-understanding/styles.ts
Labels: Approved to merge

#2673 fix: support the cross train corner case
  Composer/packages/client/__tests__/utils/luUtil.test.ts
  Composer/packages/client/package.json
  Composer/packages/client/src/utils/luUtil.ts
  Composer/packages/lib/bot-deploy/package.json
  Composer/packages/lib/indexers/package.json
  Composer/packages/lib/indexers/src/dialogUtils/extractIntentTriggers.ts
  Composer/packages/server/package.json
  Composer/packages/tools/language-servers/language-understanding/package.json
  Composer/yarn.lock
Labels: Approved to merge

#2734 a11y: use useShell for global announcements
  Composer/packages/client/src/pages/language-generation/table-view.tsx
  Composer/packages/client/src/shell/useShell.ts
  Composer/packages/client/src/store/action/error.ts
  Composer/packages/extensions/adaptive-form/src/components/fields/ObjectArrayField.tsx
  Composer/packages/lib/shared/src/types/shell.ts
Labels: Approved to merge

#2629 feat: add down sampling before luis publish
  Composer/packages/server/__tests__/controllers/project.test.ts
  Composer/packages/server/__tests__/models/bot/sampler/BootstrapSampler.test.ts
  Composer/packages/server/__tests__/models/bot/sampler/ReservoirSampler.test.ts
  Composer/packages/server/package.json
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/models/bot/luPublisher.ts
  Composer/packages/server/src/models/bot/sampler/BootstrapSampler.ts
  Composer/packages/server/src/models/bot/sampler/ReservoirSampler.ts
  Composer/packages/server/src/models/settings/defaultSettingManager.ts
  Composer/packages/server/src/models/settings/fileSettingManager.ts
  Composer/yarn.lock
Labels: Approved to merge

#2679 feat: make runtime configurable
  BotProject/Templates/CSharp/BotProject.csproj
  BotProject/Templates/CSharp/BotSettings/BlobStorageConfiguration.cs
  BotProject/Templates/CSharp/BotSettings/BotFeatureSettings.cs
  BotProject/Templates/CSharp/BotSettings/BotSettings.cs
  BotProject/Templates/CSharp/ComposerBot.cs
  BotProject/Templates/CSharp/Scripts/deploy.ps1
  BotProject/Templates/CSharp/Startup.cs
  BotProject/Templates/CSharp/Tests/ActionsTests.cs
  BotProject/Templates/CSharp/appsettings.json
  Composer/packages/server/src/models/settings/defaultSettingManager.ts
Labels: Approved to merge

#2774 fix: unexpected lg name replacement in dialog dataTime
  Composer/packages/lib/shared/src/lgUtils/parsers/lgPatterns.ts
  Composer/packages/server/src/models/bot/botProject.ts
Labels: Approved to merge

#2786 fix: unexpected file changes when editing
  Composer/packages/server/__tests__/controllers/project.test.ts
  Composer/packages/server/src/controllers/project.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/services/project.ts
Labels: Needs review
