Repository microsoft/BotFramework-Composer, pull requests merged in 2021-03, with the labels that each got.

#5669 feat: abs handoff in composer
  Composer/packages/client/src/components/CreationFlow/CreateOptions.tsx
  Composer/packages/client/src/components/CreationFlow/CreationFlow.tsx
  Composer/packages/client/src/components/CreationFlow/DefineConversation.tsx
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/utils/electronUtil.ts
  Composer/packages/electron-server/src/utility/url.ts
  Composer/packages/server/src/controllers/project.ts
  Composer/packages/server/src/externalContentProvider/contentProviderFactory.ts
  Composer/packages/server/src/services/project.ts
  Composer/packages/types/src/publish.ts
  extensions/azurePublish/package.json
  extensions/azurePublish/src/node/azureResourceManager/azureResourceManager.ts
  extensions/azurePublish/src/node/azureResourceManager/azureResourceManagerConfig.ts
  extensions/azurePublish/src/node/deploy.ts
  extensions/azurePublish/src/node/index.ts
  extensions/azurePublish/src/node/keyvaultHelper/keyvaultApi.ts
  extensions/azurePublish/src/node/keyvaultHelper/keyvaultApiConfig.ts
  extensions/azurePublish/src/node/provision.test.ts
  extensions/azurePublish/src/node/provision.ts
  extensions/azurePublish/src/node/utils/errorHandler.ts
  extensions/azurePublish/yarn.lock
  yarn.lock
Labels: 1.4

#6004 fix: get diagnostics data for different project not work
  Composer/packages/client/src/components/NavTree.tsx
  Composer/packages/client/src/components/Page.tsx
  Composer/packages/client/src/pages/diagnostics/Diagnostics.tsx
  Composer/packages/client/src/pages/diagnostics/DiagnosticsTable.tsx
Labels: 1.4

#5909 feature: Add support for MSA authentication
  Composer/packages/client/src/plugins/api.ts
  Composer/packages/client/src/utils/authClient.ts
  Composer/packages/electron-server/__tests__/auth/oneAuthService.test.ts
  Composer/packages/electron-server/src/auth/oneAuthService.ts
  Composer/packages/electron-server/src/auth/oneAuthShim.ts
  Composer/packages/electron-server/src/main.ts
  Composer/packages/extension-client/src/auth/index.ts
  Composer/packages/server/src/controllers/auth.ts
  Composer/packages/server/src/router/api.ts
  Composer/packages/server/src/utility/electronContext.ts
  Composer/packages/types/src/azure.ts
  Composer/packages/types/src/index.ts
Labels: 1.4

#5999 chore: remove $kind restriction on Flow Editor layouter
  Composer/packages/adaptive-flow/__tests__/adaptive-flow-renderer/transformers/transformForeach.test.ts
  Composer/packages/adaptive-flow/__tests__/adaptive-flow-renderer/transformers/transformIfCondition.test.ts
  Composer/packages/adaptive-flow/__tests__/adaptive-flow-renderer/transformers/transformSwitchCondition.test.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/configs/buitinNowrapWidgetNames.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/constants/AdaptiveKinds.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/transformers/transformForeach.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/transformers/transformIfCondition.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/transformers/transformSwitchCondition.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/AdaptiveAction.tsx
Labels: 1.4

#6032 fix: Orchestrator downloads multi-language model when it is not needed
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/orchestrator.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/orchestrator.ts
Labels: 1.4

#5741 feat: appended provision with a profile
  Composer/packages/client/__tests__/pages/botProjectsSettings/PublishTarget.test.tsx
  Composer/packages/client/src/pages/botProject/PublishTargets.tsx
  Composer/packages/client/src/pages/botProject/create-publish-profile/EditProfileDialog.tsx
  Composer/packages/client/src/pages/botProject/create-publish-profile/ProfileFormDialog.tsx
  Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx
  Composer/packages/client/src/recoilModel/dispatchers/provision.ts
  Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
  Composer/packages/client/src/utils/publishStatusPollingUpdater.ts
  Composer/packages/server/src/locales/en-US.json
  extensions/azurePublish/src/components/api.tsx
  extensions/azurePublish/src/components/azureProvisionDialog.tsx
  extensions/azurePublish/src/components/images/QnA-Maker.svg
  extensions/azurePublish/src/components/images/index.ts
  extensions/azurePublish/src/node/azureResourceManager/azureResourceManager.ts
  extensions/azurePublish/src/node/index.ts
  extensions/azurePublish/src/node/provision.test.ts
  extensions/azurePublish/src/node/provision.ts
  extensions/azurePublish/src/node/schema.ts
  extensions/azurePublish/src/types/index.ts
Labels: 1.4, Team: Runtime & Publishing

#5939 feat: add a new getting started section at the top of bot settings
  Composer/packages/client/__tests__/pages/botProjectsSettings/DeleteBotButton.test.tsx
  Composer/packages/client/src/components/GetStarted/GetStarted.tsx
  Composer/packages/client/src/components/GetStarted/styles.ts
  Composer/packages/client/src/components/Page.tsx
  Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
  Composer/packages/client/src/pages/botProject/BotProjectSettingsTableView.tsx
  Composer/packages/client/src/pages/botProject/DeleteBotButton.tsx
  Composer/packages/client/src/pages/extensions/ExtensionsPage.tsx
  Composer/packages/client/src/pages/home/Home.tsx
  Composer/packages/client/src/pages/publish/PublishToolbar.tsx
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/lib/ui-shared/src/components/Toolbar.tsx
  Composer/packages/types/src/telemetry.ts
Labels: topic: creation

#6076 fix: Don't prompt for LUIS key if not needed
  Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
  Composer/packages/client/src/recoilModel/selectors/diagnosticsPageSelector.ts
  Composer/packages/client/src/recoilModel/selectors/project.ts
Labels: 1.4

#5920 feat: update dotnet sdk package to 4.12.0-rc1, js sdk.schema to 4.12.0-rc3
  Composer/packages/server/schemas/sdk.schema
  Composer/packages/server/schemas/sdk.uischema
  Composer/packages/types/src/schema.ts
  Composer/packages/ui-plugins/composer/src/defaultFlowSchema.ts
  Composer/packages/ui-plugins/composer/src/defaultMenuSchema.ts
  runtime/dotnet/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
  runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
  runtime/dotnet/core/Microsoft.BotFramework.Composer.Core.csproj
  runtime/dotnet/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj
  runtime/node/schemas/sdk.schema
  runtime/node/schemas/sdk.uischema
Labels: 1.4

#5737 fix: add subscription id to json editor schema
  extensions/azurePublish/src/node/schema.ts
Labels: 1.4

#5810 doc: update/provision+publish/readmes
  extensions/samples/assets/shared/README.md
  extensions/samples/assets/shared/media/create-azure-resource-command-line.png
  extensions/samples/assets/shared/media/publish-az-login.png
  runtime/dotnet/azurewebapp/Scripts/deploy.ps1
  runtime/dotnet/azurewebapp/Scripts/readme.md
Labels: 1.4

#6069 fix: properly truncate long versions in install button
  extensions/packageManager/src/pages/Library.tsx
Labels: 1.4, topic: package manager

#6030 chore: automated localization updates
  Composer/packages/electron-server/locales/nl.json
  Composer/packages/electron-server/locales/tr.json
  Composer/packages/server/schemas/sdk.fr.schema
  Composer/packages/server/schemas/sdk.fr.uischema
  Composer/packages/server/schemas/sdk.it.schema
  Composer/packages/server/schemas/sdk.it.uischema
  Composer/packages/server/schemas/sdk.nl.schema
  Composer/packages/server/schemas/sdk.tr.schema
  Composer/packages/server/src/locales/cs.json
  Composer/packages/server/src/locales/de.json
  Composer/packages/server/src/locales/es.json
  Composer/packages/server/src/locales/fr.json
  Composer/packages/server/src/locales/hu.json
  Composer/packages/server/src/locales/it.json
  Composer/packages/server/src/locales/ja.json
  Composer/packages/server/src/locales/ko.json
  Composer/packages/server/src/locales/nl.json
  Composer/packages/server/src/locales/pl.json
  Composer/packages/server/src/locales/pt-BR.json
  Composer/packages/server/src/locales/pt-PT.json
  Composer/packages/server/src/locales/ru.json
  Composer/packages/server/src/locales/sv.json
  Composer/packages/server/src/locales/tr.json
  Composer/packages/server/src/locales/zh-Hans.json
  Composer/packages/server/src/locales/zh-Hant.json
Labels: 1.4

#6024 feature: adapter packages can be downloaded and configured
  Composer/package.json
  Composer/packages/adaptive-form/src/components/AdaptiveForm.tsx
  Composer/packages/client/__tests__/pages/botProjectsSettings/AdapterSettings.test.tsx
  Composer/packages/client/package.json
  Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx
  Composer/packages/client/src/pages/botProject/BotLanguage.tsx
  Composer/packages/client/src/pages/botProject/BotProjectSettingsTableView.tsx
  Composer/packages/client/src/pages/botProject/PublishTargets.tsx
  Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
  Composer/packages/client/src/pages/botProject/RuntimeSettings.tsx
  Composer/packages/client/src/pages/botProject/SkillBotExternalService.tsx
  Composer/packages/client/src/pages/botProject/SkillHostEndPoint.tsx
  Composer/packages/client/src/pages/botProject/adapters/ABSChannelSpeechModal.tsx
  Composer/packages/client/src/pages/botProject/adapters/ABSChannels.tsx
  Composer/packages/client/src/pages/botProject/adapters/AdapterSection.tsx
  Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx
  Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterSettings.tsx
  Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
  Composer/packages/client/src/pages/botProject/runtime-settings/style.ts
  Composer/packages/client/src/pages/botProject/styles.ts
  Composer/packages/server/schemas/sdk.en-US.schema
  Composer/packages/server/schemas/sdk.en-US.uischema
  Composer/packages/server/src/locales/en-US.json
  Composer/packages/types/src/schema.ts
  Composer/yarn.lock
  extensions/packageManager/src/node/feeds/feedFactory.ts
  extensions/packageManager/src/node/feeds/feedInterfaces.ts
  extensions/packageManager/src/node/feeds/npm/npmFeed.ts
  extensions/packageManager/src/node/feeds/nuget/localNuGetFeed.ts
  extensions/packageManager/src/node/feeds/nuget/nugetFeed.ts
  extensions/packageManager/src/node/feeds/nuget/nugetInterfaces.ts
  extensions/packageManager/src/node/index.ts
Labels: Area: Adapters

#6077 fix: template selection design fixes
  Composer/packages/client/src/components/CreationFlow/v2/CreateOptions.tsx
  Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
Labels: 1.4, topic: creation

#6104 fix: select luis region will make the review page white screen
  extensions/azurePublish/src/components/azureProvisionDialog.tsx
Labels: 1.4, topic: publish

#6111 fix: publish is successful however a failure is being reported in the notifications pane
  Composer/packages/client/src/pages/publish/Publish.tsx
Labels: 1.4

#6118 fix: give adapter section a unique scrollToId
  Composer/packages/client/src/pages/botProject/adapters/AdapterSection.tsx
Labels: 1.4, R12 Bugbash

#6121 fix: redesign get started widget to solve some ux problems
  Composer/packages/client/src/components/GetStarted/GetStarted.tsx
  Composer/packages/client/src/components/GetStarted/styles.ts
  Composer/packages/client/src/components/Page.tsx
  Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/server/src/locales/en-US.json
Labels: 1.4

#6105 fix: hide BotController in home page
  Composer/packages/client/src/components/Header.tsx
  Composer/packages/client/src/hooks/useControllerBar.ts
Labels: 1.4

#6251 fix: Webchat Inspector behavior
  Composer/cypress/integration/LuisDeploy.spec.ts
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/Header.tsx
  Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
  Composer/packages/client/src/components/WebChat/__tests__/WebchatPanel.test.tsx
  Composer/packages/client/src/pages/design/DebugPanel/DebugPanel.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsTabContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/types.ts
  Composer/packages/client/src/pages/design/DebugPanel/styles.ts
  Composer/packages/client/src/pages/design/__tests__/WebChatLogContent.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/application.ts
  Composer/packages/client/src/recoilModel/dispatchers/webchat.ts
Labels: 1.4

#6238 fix: import lg/lu not find all up view
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/pages/language-generation/code-editor.tsx
  Composer/packages/client/src/pages/language-generation/table-view.tsx
  Composer/packages/client/src/pages/language-understanding/code-editor.tsx
  Composer/packages/client/src/pages/language-understanding/table-view.tsx
  Composer/packages/client/src/recoilModel/selectors/dialogImports.ts
Labels: 1.4

#6240 fix: move orchestrator build to worker
  Composer/packages/server/src/models/bot/__tests__/orchestratorBuilder.test.ts
  Composer/packages/server/src/models/bot/builder.ts
  Composer/packages/server/src/models/bot/process/orchestratorBuilder.ts
  Composer/packages/server/src/models/bot/process/orchestratorWorker.ts
  Composer/packages/server/src/models/bot/process/types.ts
Labels: 1.4

#5749 fix: disable LUIS directVersionPublish
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/models/bot/builder.ts
  Composer/packages/server/src/models/settings/defaultSettingManager.ts
  Composer/packages/types/src/settings.ts
Labels: 1.4

#6112 fix: enable personal account.
  Composer/packages/client/src/pages/botProject/create-publish-profile/ProfileFormDialog.tsx
  Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx
  Composer/packages/client/src/pages/publish/Publish.tsx
  Composer/packages/client/src/plugins/api.ts
  Composer/packages/client/src/utils/auth.ts
  Composer/packages/client/src/utils/authClient.ts
  Composer/packages/electron-server/__tests__/auth/oneAuthService.test.ts
  Composer/packages/electron-server/src/auth/oneAuthService.ts
  Composer/packages/extension-client/src/hooks/usePublishApi.ts
  extensions/azurePublish/src/components/azureProvisionDialog.tsx
  extensions/azurePublish/src/components/util.ts
Labels: 1.4

#6331 fix: Bot should not be blocked from running if there potential syntax error for lg custom function
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/dialog.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/multilang.test.tsx
  Composer/packages/client/src/recoilModel/selectors/lg.ts
  Composer/packages/client/src/utils/lgUtil.ts
  Composer/packages/lib/indexers/src/utils/lgUtil.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/index.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/validation.ts
  Composer/packages/types/src/settings.ts
Labels: 1.4

#6323 fix: moved long running creation steps to worker threads to prevent main process overload
  Composer/packages/server/package.json
  Composer/packages/server/src/locales/en-US.json
  Composer/packages/server/src/models/asset/__tests__/assetManager.test.ts
  Composer/packages/server/src/models/asset/assetManager.ts
  Composer/packages/server/src/services/project.ts
  Composer/packages/server/src/utility/project.ts
  Composer/packages/server/src/workers/dialogMerge.worker.ts
  Composer/packages/server/src/workers/templateInstallation.worker.ts
Labels: 1.4, topic: creation

#6307 fix: Orchestrator publishing settings were wrong (legacy runtime)
  Composer/packages/server/src/models/bot/builder.ts
  Composer/packages/server/src/models/bot/interface.ts
  extensions/azurePublish/src/node/deploy.ts
  extensions/azurePublish/src/node/luisAndQnA.ts
Labels: 1.4

#6354 chore: project tree flatten imports
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/pages/language-understanding/table-view.tsx
  Composer/packages/client/src/recoilModel/selectors/__test__/dialogImports.test.tsx
  Composer/packages/client/src/recoilModel/selectors/dialogImports.ts
  Composer/packages/client/src/recoilModel/selectors/project.ts
Labels: 1.4

#5710 chore: fix several uischema hook issues
  Composer/packages/extension-client/src/hooks/__tests__/useMenuConfig.test.tsx
  Composer/packages/extension-client/src/hooks/useFormConfig.ts
  Composer/packages/extension-client/src/hooks/useMenuConfig.ts
  Composer/packages/extension-client/src/hooks/useTriggerConfig.ts
  Composer/packages/lib/shared/src/lgUtils/stringBuilders/buildLgType.ts
  Composer/packages/lib/shared/src/luNameBuilder/stringBuilders/buildLuType.ts
Labels: 1.4, R12, Team: Authoring

#6236 feat: update dotnet sdk version from 4.12.0-rc1 -> 4.12.0
  Composer/packages/server/schemas/sdk.schema
  runtime/dotnet/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
  runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
  runtime/dotnet/core/Microsoft.BotFramework.Composer.Core.csproj
  runtime/dotnet/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj
Labels: 1.4

#6212 feat: add telemetry to package manager
  Composer/packages/types/src/telemetry.ts
  extensions/packageManager/src/components/FeedModal.tsx
  extensions/packageManager/src/pages/Library.tsx
Labels: 1.4

#6346 fix: Change identifier used for the new runtime
  Composer/packages/server/src/models/extension/extensionContext.ts
  extensions/azurePublish/src/node/index.ts
  extensions/runtimes/src/index.ts
Labels: 1.4

#6219 fix: allow multiple feeds with same url to co-exist
  extensions/packageManager/src/components/FeedModal.tsx
  extensions/packageManager/src/components/ImportDialog.tsx
  extensions/packageManager/src/node/index.ts
  extensions/packageManager/src/pages/Library.tsx
Labels: 1.4, topic: package manager

#6237 fix: change provision script to support abs azure bot
  extensions/azurePublish/src/node/azureResourceManager/azureResourceManager.ts
  extensions/samples/assets/shared/scripts/DeploymentTemplates/template-with-preexisting-rg.json
Labels: 1.4

#6349 fix: enable deep link from ABS to work as expected with new creation flow
  Composer/packages/client/src/components/CreationFlow/CreateOptions.tsx
  Composer/packages/client/src/components/CreationFlow/CreationFlow.tsx
  Composer/packages/client/src/components/CreationFlow/v2/CreateOptions.tsx
  Composer/packages/client/src/components/CreationFlow/v2/CreationFlow.tsx
  Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/server/src/services/project.ts
Labels: 1.4

#6373 fix: add cache for orchestrator build to reduce the re-build time
  Composer/packages/server/src/models/bot/__tests__/orchestratorBuilder.test.ts
  Composer/packages/server/src/models/bot/builder.ts
  Composer/packages/server/src/models/bot/process/orchestratorBuilder.ts
  Composer/packages/server/src/models/bot/process/orchestratorWorker.ts
  Composer/packages/server/src/models/bot/process/types.ts
Labels: 1.4, Area: Orchestrator

#6369 fix: Orchestrator don't show notification if model already exists
  Composer/packages/client/src/recoilModel/dispatchers/orchestrator.ts
  Composer/packages/server/src/controllers/orchestrator.ts
Labels: 1.4, Area: Orchestrator

#6370 fix: Should not show LUIS locale warnings if bot is exclusively using Orchestrator
  Composer/packages/lib/indexers/src/botIndexer.ts
Labels: 1.4, Area: Orchestrator

#6208 fix: change links based on bug-bash suggestions
  Composer/packages/client/__tests__/pages/botProjectsSettings/AdapterSettings.test.tsx
  Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx
  Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterSettings.tsx
  Composer/packages/server/src/locales/en-US.json
Labels: 1.4

#6368 feat: Add telemetry to track if Composer was opened from PVA or ABS
  Composer/packages/client/src/telemetry/useInitializeLogger.ts
  Composer/packages/types/src/telemetry.ts
Labels: 1.4

#6380 fix: read plugin config for action names in breadcrumb array
  Composer/packages/client/src/pages/design/VisualPanelHeader.tsx
Labels: 1.4

#6378 fix: qna template to create right empty bot generator
  Composer/packages/lib/shared/src/constant.ts
  Composer/packages/server/src/controllers/asset.ts
  Composer/packages/server/src/models/asset/assetManager.ts
Labels: 1.4

#6388 fix: Fixed issue inserting functions in LG
  Composer/packages/lib/code-editor/src/lg/modalityEditors/StringArrayEditor.tsx
  Composer/packages/lib/code-editor/src/lg/modalityEditors/StringArrayItem.tsx
Labels: 1.4

#6401 fix: react-dev-utils version
  Composer/packages/client/package.json
  Composer/packages/client/scripts/start.js
  Composer/yarn.lock
Labels: 1.4

#6405 fix: Remove Attachment Lg template when they are deleted in the Response Editor
  Composer/packages/lib/code-editor/src/lg/modalityEditors/AttachmentArrayEditor.tsx
  Composer/packages/lib/code-editor/src/lg/modalityEditors/AttachmentModalityEditor.tsx
  Composer/packages/lib/code-editor/src/lg/modalityEditors/StringArrayItem.tsx
  Composer/packages/server/src/locales/en-US.json
Labels: 1.4, P0

#6414 fix: Added gray Composer icon to 'no triggers' dialog state
  Composer/packages/client/src/pages/design/VisualEditor.tsx
Labels: 1.4-RC1

#6415 fix: revert yeoman-environment to 2.10.3 from 3.1.0
  Composer/packages/server-workers/package.json
Labels: 1.4-RC1

#6427 fix: use new create flow during add skill if enabled
  Composer/packages/client/src/components/CreationFlow/v2/CreateOptions.tsx
  Composer/packages/client/src/pages/design/creationModal.tsx
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/server/src/controllers/project.ts
  Composer/yarn.lock
Labels: 1.4-RC2, P0

#6432 fix: load feature flags if default keys have changed
  Composer/packages/client/src/recoilModel/dispatchers/storage.ts
  Composer/packages/server/src/services/featureFlags.ts
Labels: 1.4-RC2

#6435 fix: Orchestrator labels get corrupted with entity data upon successive training
  Composer/packages/server/package.json
  Composer/yarn.lock
Labels: 1.4-RC2

#6437 fix: Fixing projectId state save for new creation flow
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
Labels: 1.4-RC2

#6444 fix: hidden showCode button when url is all & show code for form dialog
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/pages/language-understanding/table-view.tsx
  Composer/packages/client/src/router.tsx
Labels: 1.4-RC2

#6520 fix: unify runtime path from ejecting
  Composer/packages/server/src/models/bot/botProject.ts
  extensions/runtimes/src/index.ts
Labels: Approved to merge

#6568 fix: Lu editing improvement fixes
  Composer/packages/adaptive-form/src/components/fields/IntentField.tsx
  Composer/packages/client/src/components/TriggerCreationModal/TriggerCreationModal.tsx
  Composer/packages/client/src/components/TriggerCreationModal/resolveTriggerWidget.tsx
  Composer/packages/extension-client/src/hooks/useRecognizerConfig.ts
  Composer/packages/lib/code-editor/src/lu/LuLabelingMenu.tsx
  Composer/packages/server/src/locales/en-US.json
Labels: Area: LU, LU Editor
