Repository microsoft/BotFramework-Composer, pull requests merged in 2021-01, with the labels that each got.

#5455 fix: LG worker cache expires occasionally
  Composer/packages/client/src/recoilModel/parsers/workers/lgParser.worker.ts
  Composer/packages/lib/indexers/src/utils/lgUtil.ts
Labels: Area: Perf

#5471 fix: Remove native Orchestrator DLLs from Runtime
  runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
  runtime/dotnet/azurewebapp/Startup.cs
  runtime/dotnet/core/ComposerSettingsExtensions.cs
Labels: 1.3Patch

#5440 fix: fix australia region not work when publishing luis
  Composer/packages/client/src/constants.ts
  Composer/packages/server/src/locales/en-US.json
Labels: 1.3Patch

#5457 fix: mutli re-render when editing in form editor
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/shell/lgApi.ts
  Composer/packages/client/src/shell/luApi.ts
Labels: 1.3Patch, Area: Perf

#5466 chore: Avoid re-render from states value change
  Composer/packages/client/src/pages/knowledge-base/QnAPage.tsx
  Composer/packages/client/src/pages/knowledge-base/code-editor.tsx
  Composer/packages/client/src/pages/knowledge-base/table-view.tsx
  Composer/packages/client/src/pages/language-generation/LGPage.tsx
  Composer/packages/client/src/pages/language-generation/table-view.tsx
  Composer/packages/client/src/pages/language-understanding/LUPage.tsx
  Composer/packages/client/src/pages/language-understanding/table-view.tsx
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/packages/client/src/router.tsx
Labels: 1.3Patch, Area: Perf

#5463 chore: Performance improvements for ProjectTree
  Composer/package.json
  Composer/packages/client/src/components/BotRuntimeController/publishDialog.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectHeader.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/components/ProjectTree/helpers.ts
  Composer/packages/client/src/components/ProjectTree/treeItem.tsx
  Composer/packages/client/src/components/RepairSkillModal.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/trigger.test.tsx
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/yarn.lock
Labels: 1.3Patch, Area: Perf

#5481 docs: Update Orchestrator requirement docs in prep for Composer 1.3.1
  docs/1.3-supported-os.md
  docs/preview features/orchestrator-assets/add-trigger.png
  docs/preview features/orchestrator-assets/application-settings.png
  docs/preview features/orchestrator-assets/create-intent-trigger.png
  docs/preview features/orchestrator-assets/eject-runtime.png
  docs/preview features/orchestrator-assets/emulator.png
  docs/preview features/orchestrator-assets/orchestrator-recognizer-dropdown.png
  docs/preview features/orchestrator-assets/preview-flag-orchestrator.png
  docs/preview features/orchestrator.md
Labels: 1.3Patch, type: docs

#5475 fix: Revert to reopening a resource
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
Labels: 1.3Patch

#5483 fix: validate dialog take a long time when updating lg in form
  Composer/packages/client/__tests__/pages/language-generation/LGPage.test.tsx
  Composer/packages/client/__tests__/pages/notifications/diagnosticList.test.tsx
  Composer/packages/client/__tests__/pages/notifications/diagnostics.test.tsx
  Composer/packages/client/__tests__/shell/lgApi.test.tsx
  Composer/packages/client/__tests__/shell/triggerApi.test.tsx
  Composer/packages/client/src/Onboarding/Onboarding.tsx
  Composer/packages/client/src/components/BotRuntimeController/publishDialog.tsx
  Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
  Composer/packages/client/src/hooks/useResolver.ts
  Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
  Composer/packages/client/src/pages/botProject/SkillBotExternalService.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/pages/design/PropertyEditor.tsx
  Composer/packages/client/src/pages/design/VisualEditor.tsx
  Composer/packages/client/src/pages/design/createDialogModal.tsx
  Composer/packages/client/src/pages/design/exportSkillModal/content/SelectDialogs.tsx
  Composer/packages/client/src/pages/language-generation/code-editor.tsx
  Composer/packages/client/src/pages/language-generation/table-view.tsx
  Composer/packages/client/src/pages/language-understanding/table-view.tsx
  Composer/packages/client/src/recoilModel/DispatcherWrapper.tsx
  Composer/packages/client/src/recoilModel/atoms/botState.ts
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/dialog.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/lg.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/multilang.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/project.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/trigger.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/dialogs.ts
  Composer/packages/client/src/recoilModel/dispatchers/lg.ts
  Composer/packages/client/src/recoilModel/dispatchers/multilang.ts
  Composer/packages/client/src/recoilModel/dispatchers/trigger.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/recoilModel/selectors/diagnosticsPageSelector.ts
  Composer/packages/client/src/recoilModel/selectors/dialogImports.ts
  Composer/packages/client/src/recoilModel/selectors/index.ts
  Composer/packages/client/src/recoilModel/selectors/lg.ts
  Composer/packages/client/src/recoilModel/selectors/localRuntimeBuilder.ts
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/packages/client/src/recoilModel/selectors/validatedDialogs.ts
  Composer/packages/client/src/recoilModel/undo/__test__/history.test.tsx
  Composer/packages/client/src/recoilModel/undo/trackedAtoms.ts
  Composer/packages/client/src/shell/useShell.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/index.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/types.ts
  Composer/packages/lib/indexers/src/validations/expressionValidation/validation.ts
  Composer/packages/lib/indexers/src/validations/index.ts
Labels: 1.3Patch, Area: Perf

#5493 fix: telemetry fixes
  Composer/packages/client/src/telemetry/useInitializeLogger.ts
  Composer/packages/client/src/utils/getPageName.tsx
  Composer/packages/server/src/constants.ts
Labels: 1.3Patch

#5517 fix: bump version to 1.3.1
  Composer/packages/client/config/env.js
  Composer/packages/electron-server/package.json
  Composer/packages/server/src/constants.ts
Labels: 1.3Patch

#5524 fix: switching in project tree is lagging
  Composer/packages/client/src/App.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/pages/design/VisualEditorHeader.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/navigation.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/navigation.ts
Labels: 1.3Patch

#5563 fix: Move persistence layer's delta computation into worker
  Composer/packages/client/src/recoilModel/parsers/fileDiffCalculator.ts
  Composer/packages/client/src/recoilModel/parsers/types.ts
  Composer/packages/client/src/recoilModel/parsers/workers/calculator.worker.ts
  Composer/packages/client/src/recoilModel/persistence/FilePersistence.ts
  Composer/packages/client/src/recoilModel/persistence/__test__/FilePersistence.test.ts
  Composer/packages/client/src/recoilModel/persistence/types.ts
Labels: Area: Perf, Needs review
