Repository microsoft/BotFramework-Composer, pull requests merged in 2021-02, with the labels that each got.

#5474 fix: unify display name function in client, visual editor
  Composer/cypress/integration/RemoveDialog.spec.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/TriggerSummary/TriggerSummary.tsx
  Composer/packages/client/__tests__/utils/dialogUtil.test.js
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/pages/design/VisualPanelHeader.tsx
  Composer/packages/client/src/pages/design/exportSkillModal/content/SelectTriggers.tsx
  Composer/packages/client/src/utils/dialogUtil.ts
  Composer/packages/lib/indexers/src/dialogIndexer.ts
  Composer/packages/lib/shared/src/dialogFactory.ts
Labels: Needs review

#4647 feat: add more extension api hooks
  Composer/packages/adaptive-flow/__tests__/adaptive-flow-editor/stubs/ShellApiStub.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useEditorEventApi.ts
  Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx
  Composer/packages/client/src/plugins/api.ts
  Composer/packages/client/src/shell/useShell.ts
  Composer/packages/extension-client/src/hooks/index.ts
  Composer/packages/extension-client/src/hooks/useApplicationApi.ts
  Composer/packages/extension-client/src/hooks/useDialogApi.ts
  Composer/packages/extension-client/src/hooks/useLgApi.ts
  Composer/packages/extension-client/src/hooks/useLuApi.ts
  Composer/packages/extension-client/src/hooks/useProjectApi.ts
  Composer/packages/extension-client/src/hooks/usePublishApi.ts
  Composer/packages/extension-client/src/index.ts
  Composer/packages/extension-client/src/publish/index.ts
  Composer/packages/extension-client/src/publish/types.ts
  Composer/packages/extension-client/src/utils/validateHookContext.ts
  Composer/packages/types/src/shell.ts
  extensions/azurePublish/src/components/azureProvisionDialog.tsx
  extensions/azurePublish/yarn.lock
  extensions/pvaPublish/src/components/pvaDialog.tsx
  extensions/pvaPublish/testing/setupUITests.js
  extensions/sample-ui-plugin/src/components/main.tsx
Labels: Area: Extension, Not Targetting Main

#5722 feat: apply new deisgn on project tree to solve Critical create actions inaccessible issue on Project Tree
  Composer/packages/client/src/components/ProjectTree/ExpandableNode.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectHeader.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/components/ProjectTree/constants.ts
  Composer/packages/client/src/components/ProjectTree/helpers.ts
  Composer/packages/client/src/components/ProjectTree/treeItem.tsx
Labels: Team: Authoring

#5707 feat: Change editors to default monospaced fonts, adds <FontSettings />
  Composer/packages/client/__tests__/components/appSettings.test.tsx
  Composer/packages/client/src/pages/setting/app-settings/AppSettings.tsx
  Composer/packages/client/src/pages/setting/app-settings/fontSettings.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/user.test.ts
  Composer/packages/client/src/recoilModel/utils/index.ts
  Composer/packages/lib/code-editor/src/BaseEditor.tsx
  Composer/packages/types/src/settings.ts
  Composer/packages/types/src/shell.ts
  Composer/packages/ui-plugins/lg/src/LgField.tsx
  Composer/packages/ui-plugins/luis/src/LuisIntentEditor.tsx
Labels: Approved to merge

#5815 chore: Upgrade pipelines to Node LTS
  .github/workflows/main.yml
  Composer/packages/server/src/utility/__tests__/npm.test.ts
  azure-pipelines.yml
Labels: 1.4, P0, R12, Team: Platform

#5716 feat: Mock Directline Extension
  Composer/packages/server/package.json
  Composer/packages/server/src/directline/middleware/__tests__/conversationHandler.test.ts
  Composer/packages/server/src/directline/middleware/__tests__/createBotFrameworkAuthentication.test.ts
  Composer/packages/server/src/directline/middleware/__tests__/createGetConversationHandler.test.ts
  Composer/packages/server/src/directline/middleware/__tests__/createNewConversationHandler.test.ts
  Composer/packages/server/src/directline/middleware/__tests__/createUploadHandler.test.ts
  Composer/packages/server/src/directline/middleware/conversationHandler.ts
  Composer/packages/server/src/directline/middleware/createBotEndpoint.ts
  Composer/packages/server/src/directline/middleware/createBotFrameworkAuthentication.ts
  Composer/packages/server/src/directline/middleware/createGetConversationHandler.ts
  Composer/packages/server/src/directline/middleware/createNewConversationHandler.ts
  Composer/packages/server/src/directline/middleware/createUploadHandler.ts
  Composer/packages/server/src/directline/middleware/index.ts
  Composer/packages/server/src/directline/middleware/transcriptHandler.ts
  Composer/packages/server/src/directline/mountConversationRoutes.ts
  Composer/packages/server/src/directline/mountDirectlineRoutes.ts
  Composer/packages/server/src/directline/store/dlServerState.ts
  Composer/packages/server/src/directline/store/entities/__tests__/attachments.test.ts
  Composer/packages/server/src/directline/store/entities/__tests__/conversation.test.ts
  Composer/packages/server/src/directline/store/entities/__tests__/conversationSet.test.ts
  Composer/packages/server/src/directline/store/entities/__tests__/endpointSet.test.ts
  Composer/packages/server/src/directline/store/entities/attachments.ts
  Composer/packages/server/src/directline/store/entities/botEndpoint.ts
  Composer/packages/server/src/directline/store/entities/conversation.ts
  Composer/packages/server/src/directline/store/entities/conversationSet.ts
  Composer/packages/server/src/directline/store/entities/dataUrlEncoder.ts
  Composer/packages/server/src/directline/store/entities/endpointSet.ts
  Composer/packages/server/src/directline/store/types.ts
  Composer/packages/server/src/directline/utils/__tests__/helpers.test.ts
  Composer/packages/server/src/directline/utils/__tests__/mountConversationRoutes.test.ts
  Composer/packages/server/src/directline/utils/__tests__/openIdMetadata.test.ts
  Composer/packages/server/src/directline/utils/__tests__/webSocketServer.test.ts
  Composer/packages/server/src/directline/utils/apiErrorException.ts
  Composer/packages/server/src/directline/utils/constants.ts
  Composer/packages/server/src/directline/utils/fileOperations.ts
  Composer/packages/server/src/directline/utils/helpers.ts
  Composer/packages/server/src/directline/utils/logger.ts
  Composer/packages/server/src/directline/utils/openIdMetaData.ts
  Composer/packages/server/src/directline/utils/socketPort.ts
  Composer/packages/server/src/directline/utils/webSocketServer.ts
  Composer/packages/server/src/server.ts
  Composer/packages/test-utils/src/mergeConfig.ts
  Composer/yarn.lock
Labels: P0, R12, Team: Platform, Webchat Integration

#5686 feat: Debugging panel with integrated diagnostics data
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/components/ZoomZone.tsx
  Composer/packages/client/__tests__/pages/notifications/diagnosticList.test.tsx
  Composer/packages/client/src/pages/design/CommandBar.tsx
  Composer/packages/client/src/pages/design/DebugPanel/DebugPanel.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticList.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsStatus.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsTabContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsTabHeader.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/Indicator.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/index.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/useDiagnostics.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/index.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/index.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/types.ts
  Composer/packages/client/src/pages/design/DebugPanel/styles.ts
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/pages/design/styles.ts
  Composer/packages/client/src/pages/diagnostics/Diagnostics.tsx
  Composer/packages/client/src/pages/diagnostics/DiagnosticsTable.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/extension-client/src/extensionEventEmitter.ts
  Composer/packages/extension-client/src/index.ts
Labels: Team: Authoring, Webchat Integration

#5790 feat: Webchat Integration
  Composer/packages/client/package.json
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/Header.tsx
  Composer/packages/client/src/components/WebChat/WebChatContainer.tsx
  Composer/packages/client/src/components/WebChat/WebChatHeader.tsx
  Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
  Composer/packages/client/src/components/WebChat/__tests__/WebchatPanel.test.tsx
  Composer/packages/client/src/components/WebChat/utils/conversationService.ts
  Composer/packages/client/src/components/WebChat/utils/webChatTheme.ts
  Composer/packages/client/src/components/__tests__/BotRuntimeController/BotController.test.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/recoilModel/selectors/localRuntimeBuilder.ts
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/packages/electron-server/src/main.ts
  Composer/packages/extension/src/extensionRegistration.ts
  Composer/packages/server/package.json
  Composer/packages/server/src/directline/middleware/__tests__/attachmentHandler.test.ts
  Composer/packages/server/src/directline/middleware/__tests__/conversationHandler.test.ts
  Composer/packages/server/src/directline/middleware/attachmentHandler.ts
  Composer/packages/server/src/directline/middleware/conversationHandler.ts
  Composer/packages/server/src/directline/middleware/createNewConversationHandler.ts
  Composer/packages/server/src/directline/middleware/createUploadHandler.ts
  Composer/packages/server/src/directline/mountAttachmentRoutes.ts
  Composer/packages/server/src/directline/mountConversationRoutes.ts
  Composer/packages/server/src/directline/store/entities/conversation.ts
  Composer/packages/server/src/directline/store/entities/conversationSet.ts
  Composer/packages/server/src/directline/utils/__tests__/mountAttachmentRoutes.test.ts
  Composer/packages/server/src/server.ts
  Composer/yarn.lock
Labels: R12, Team: Authoring, Webchat Integration

#5718 fix: Composer nav + button discoverability
  Composer/packages/client/src/components/Page.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx
  Composer/packages/client/src/pages/design/SideBar.tsx
Labels: P0, R12, Team: Authoring

#5733 fix: update bf-lu version to resolve app settings missing issue in luis publishing
  Composer/packages/lib/indexers/package.json
  Composer/packages/server/package.json
  Composer/packages/tools/language-servers/language-understanding/package.json
  Composer/yarn.lock
Labels: P0, Team: Platform

#5557 feat: package manager supports custom feeds, search, local feeds, multiple available versions of a package, and refreshed UI!
  Composer/packages/types/src/runtime.ts
  extensions/packageManager/package.json
  extensions/packageManager/src/client/FeedModal.tsx
  extensions/packageManager/src/client/ImportDialog.tsx
  extensions/packageManager/src/client/Library.tsx
  extensions/packageManager/src/client/LibraryList.tsx
  extensions/packageManager/src/client/WorkingModal.tsx
  extensions/packageManager/src/client/libraryList.tsx
  extensions/packageManager/src/client/projectList/ListItem.tsx
  extensions/packageManager/src/client/projectList/ProjectList.tsx
  extensions/packageManager/src/node/index.ts
  extensions/packageManager/yarn.lock
  extensions/runtimes/src/index.ts
Labels: R12, Team: Authoring

#5825 feat: add debug panel to lu/lg/qna page
  Composer/packages/client/src/components/Page.tsx
  Composer/packages/client/src/pages/diagnostics/Diagnostics.tsx
Labels: P1, Webchat Integration

#5890 fix: remove redundant suggested static luis entities
  Composer/packages/tools/language-servers/language-generation/__tests__/LGUtil.test.ts
  Composer/packages/tools/language-servers/language-generation/src/LGServer.ts
  Composer/packages/tools/language-servers/language-generation/src/lgParser.ts
  Composer/packages/tools/language-servers/language-generation/src/lgWorker.ts
Labels: 1.4

#5778 fix: Add AddNewKnowledgeBaseCompleted telemetry event to create KB from scratch
  Composer/packages/client/src/components/QnA/CreateQnAFromScratchModal.tsx
  Composer/packages/client/src/components/QnA/CreateQnAFromUrlModal.tsx
  Composer/packages/types/src/telemetry.ts
Labels: 1.4

#5936 fix: Lg Editor bus and ux improvement from bug bash
  Composer/packages/lib/code-editor/src/lg/ModalityPivot.tsx
  Composer/packages/lib/code-editor/src/lg/__tests__/ToolbarButtonMenu.test.tsx
  Composer/packages/lib/code-editor/src/lg/constants.ts
  Composer/packages/lib/code-editor/src/lg/modalityEditors/AttachmentArrayEditor.tsx
  Composer/packages/lib/code-editor/src/lg/modalityEditors/ModalityEditorContainer.tsx
  Composer/packages/lib/code-editor/src/lg/modalityEditors/StringArrayEditor.tsx
  Composer/packages/lib/code-editor/src/lg/modalityEditors/StringArrayItem.tsx
  Composer/packages/lib/code-editor/src/lg/modalityEditors/SuggestedActionsModalityEditor.tsx
  Composer/packages/lib/code-editor/src/lg/types.ts
  Composer/packages/lib/code-editor/src/utils/structuredResponse.ts
  Composer/packages/lib/ui-shared/src/components/ConfirmDialog.tsx
  Composer/packages/server/src/locales/en-US.json
  Composer/packages/tools/built-in-functions/src/builtInFunctionsGrouping.ts
  Composer/packages/ui-plugins/lg/src/LgField.tsx
Labels: 1.4, Area: Form Editor

#5886 feat: Webchat Integration bugbash and Telemetry
  Composer/packages/client/__tests__/components/BotRuntimeController/emulatorOpenButton.test.tsx
  Composer/packages/client/__tests__/pages/design/DebugPanel/DebugPanel.test.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotControllerMenu.tsx
  Composer/packages/client/src/components/BotRuntimeController/OpenEmulatorButton.tsx
  Composer/packages/client/src/components/BotRuntimeController/OpenWebChatButton.tsx
  Composer/packages/client/src/components/Header.tsx
  Composer/packages/client/src/components/WebChat/WebChatContainer.tsx
  Composer/packages/client/src/components/WebChat/WebChatHeader.tsx
  Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
  Composer/packages/client/src/components/WebChat/__tests__/WebChatContainer.test.tsx
  Composer/packages/client/src/components/WebChat/__tests__/WebChatHeader.test.tsx
  Composer/packages/client/src/components/WebChat/__tests__/WebchatPanel.test.tsx
  Composer/packages/client/src/components/WebChat/utils/conversationService.ts
  Composer/packages/client/src/pages/design/DebugPanel/DebugPanel.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticList.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsStatus.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/constants.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/index.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/index.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/types.ts
  Composer/packages/client/src/pages/design/__tests__/DebugPanel.test.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/application.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/webchat.ts
  Composer/packages/client/src/recoilModel/selectors/eject.ts
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/packages/server/src/directline/middleware/conversationHandler.ts
  Composer/packages/server/src/directline/middleware/createNewConversationHandler.ts
  Composer/packages/server/src/directline/middleware/transcriptHandler.ts
  Composer/packages/server/src/directline/store/entities/botEndpoint.ts
  Composer/packages/server/src/locales/en-US.json
  Composer/packages/types/src/telemetry.ts
Labels: 1.4, P0, R12, Webchat Integration

#5945 fix: Fixed issue with adding structured choices to choice prompts
  Composer/packages/lib/code-editor/src/BaseEditor.tsx
Labels: 1.4, Area: Form Editor

#5927 chore: Remove Orchestrator Feature Flag
  Composer/packages/lib/shared/src/featureFlagUtils/index.ts
  Composer/packages/lib/shared/src/schemaUtils/pvaSchema.ts
  Composer/packages/types/src/featureFlags.ts
  Composer/packages/ui-plugins/orchestrator/src/index.ts
Labels: 1.4, Area: Orchestrator

#5957 fix: Pass updated MSAppID and MsPass on restart
  Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
  Composer/packages/client/src/components/WebChat/utils/conversationService.ts
  Composer/packages/server/src/directline/middleware/__tests__/conversationHandler.test.ts
  Composer/packages/server/src/directline/middleware/conversationHandler.ts
  Composer/packages/server/src/directline/store/entities/botEndpoint.ts
  Composer/packages/server/src/directline/store/entities/conversation.ts
Labels: 1.4, Webchat Integration

#5926 feat: update global font settings
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogItem.tsx
  Composer/packages/client/src/pages/setting/app-settings/AppSettings.tsx
  Composer/packages/client/src/pages/setting/app-settings/fontSettings.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/user.test.ts
  Composer/packages/client/src/recoilModel/utils/fontUtil.ts
  Composer/packages/client/src/recoilModel/utils/index.ts
Labels: 1.4

#5984 feat: Support unread notification marker on Webchat inspector
  Composer/packages/client/src/pages/design/DebugPanel/DebugPanel.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsTabHeader.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogItemHeader.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/index.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/types.ts
  Composer/packages/client/src/pages/design/DebugPanel/styles.ts
  Composer/packages/client/src/recoilModel/atoms/appState.ts
Labels: 1.4, R12, Webchat Integration

#5928 fix: debug panel UX improvements
  Composer/packages/client/package.json
  Composer/packages/client/src/components/Page.tsx
  Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
  Composer/packages/client/src/pages/design/DebugPanel/DebugPanel.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DebugPanelErrorIndicator.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticList.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsStatus.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsTabContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsTabHeader.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/useDiagnostics.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogItemHeader.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/index.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/types.ts
  Composer/packages/client/src/pages/design/DebugPanel/styles.ts
  Composer/packages/client/src/pages/knowledge-base/QnAPage.tsx
  Composer/packages/client/src/pages/language-generation/LGPage.tsx
  Composer/packages/client/src/pages/language-understanding/LUPage.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/yarn.lock
Labels: 1.4, P0, Webchat Integration

#5689 fix: the recognizer dialog created is for LUIS even if Orchestrator is selected in dropdown
  Composer/packages/client/src/recoilModel/Recognizers.tsx
Labels: 1.4

#5848 fix: Orchestrator Download Notification
  Composer/packages/client/src/components/Orchestrator/DownloadNotification.tsx
  Composer/packages/client/src/recoilModel/dispatchers/index.ts
  Composer/packages/client/src/recoilModel/dispatchers/orchestrator.ts
  Composer/packages/client/src/recoilModel/selectors/localRuntimeBuilder.ts
  Composer/packages/server/src/controllers/orchestrator.ts
  Composer/packages/server/src/models/bot/builder.ts
  Composer/packages/server/src/router/api.ts
Labels: 1.4

#5878 chore: Added documentation
  docs/internal/localization.md
Labels: Team: Authoring, topic: creation

#6019 fix: Make sure advanced settings editor is to 100% height
  Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
Labels: 1.4
