Repository microsoft/BotFramework-Composer, pull requests merged in 2021-06, with the labels that each got.

#7038 fix: Add Orchestrator Debug Logging
  Composer/packages/server/src/models/bot/process/orchestratorWorker.ts
Labels: Area: Orchestrator, P2

#8035 fix: Add missing telemetry settings
  Composer/packages/lib/shared/src/settings.ts
Labels: R14, topic: telemetry

#8141 feat: Debug panel feature updates
  Composer/packages/client/__tests__/pages/design/DebugPanel/DiagnosticsContent.test.tsx
  Composer/packages/client/__tests__/pages/design/DebugPanel/diagnosticList.test.tsx
  Composer/packages/client/__tests__/pages/notifications/diagnosticFilter.test.tsx
  Composer/packages/client/__tests__/pages/notifications/diagnosticList.test.tsx
  Composer/packages/client/package.json
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/BotRuntimeController/useBotOperations.ts
  Composer/packages/client/src/components/BotRuntimeController/utils.ts
  Composer/packages/client/src/components/DiagnosticsHeader.tsx
  Composer/packages/client/src/components/DropdownWithAllOption/DropdownWithAllOption.tsx
  Composer/packages/client/src/components/ProjectTree/treeItem.tsx
  Composer/packages/client/src/components/WebChat/WebChatComposer.tsx
  Composer/packages/client/src/components/WebChat/__tests__/WebChat.test.tsx
  Composer/packages/client/src/components/WebChat/utils/WebChatTypes.d.ts
  Composer/packages/client/src/components/__tests__/BotRuntimeController/BotController.test.tsx
  Composer/packages/client/src/components/__tests__/useDebugPane.test.ts
  Composer/packages/client/src/components/useDebugPane.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticFilters.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticList.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticType.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsStatus.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsStatusFilter.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsTabContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/useAutoFix.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/useDiagnostics.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatLogContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/styles.ts
  Composer/packages/client/src/pages/diagnostics/DiagnosticFilter.tsx
  Composer/packages/client/src/pages/diagnostics/DiagnosticList.tsx
  Composer/packages/client/src/pages/diagnostics/Diagnostics.tsx
  Composer/packages/client/src/pages/diagnostics/DiagnosticsTable.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/dispatchers/application.ts
  Composer/packages/client/src/recoilModel/selectors/diagnosticsPageSelector.ts
  Composer/packages/client/src/recoilModel/selectors/dialogs.ts
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/utils/luUtil.ts
  Composer/packages/integration-tests/cypress/integration/NotificationPage.spec.ts
  Composer/packages/server/src/locales/en-US.json
  Composer/yarn.lock
Labels: Team: Authoring

#7640 fix: Orchestrator Node Install for Skill Flow
  Composer/packages/client/src/components/AddRemoteSkillModal/CreateSkillModal.tsx
  Composer/packages/client/src/components/AddRemoteSkillModal/EnableOrchestrator.tsx
  Composer/packages/client/src/components/AddRemoteSkillModal/SelectIntent.tsx
  Composer/packages/client/src/components/AddRemoteSkillModal/helper.ts
  Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx
  Composer/packages/client/src/components/Orchestrator/__tests__/OrchestratorForSkillsDialog.test.tsx
Labels: Area: Orchestrator, P0, Skills Workflow

#8191 feat: add action notes
  Composer/packages/adaptive-flow/__tests__/adaptive-flow-editor/stubs/ShellApiStub.ts
  Composer/packages/adaptive-flow/package.json
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/AdaptiveFlowEditor.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/components/FlowToolbar.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/components/ZoomZone.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/renderers/EdgeMenu/EdgeMenu.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/renderers/NodeMenu.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/renderers/NodeWrapper.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-editor/renderers/index.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/configs/builtinWidgets.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/constants/ElementSizes.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/types/PluggableComponents.types.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/ActionCard/ActionCard.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/ActionCard/ActionCardBody.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/ActionCard/CardComment.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/ActionCard/CardTemplate.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/ActionCard/CardTemplateStyle.ts
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/ActionCard/index.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/PromptWidget.tsx
  Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/index.ts
  Composer/packages/adaptive-flow/tsconfig.json
  Composer/packages/adaptive-form/package.json
  Composer/packages/adaptive-form/src/components/Comment.tsx
  Composer/packages/adaptive-form/src/components/ExpandableText.tsx
  Composer/packages/adaptive-form/src/components/FormTitle.tsx
  Composer/packages/adaptive-form/src/components/__tests__/Comment.test.tsx
  Composer/packages/adaptive-form/src/components/__tests__/ExpandableText.test.tsx
  Composer/packages/adaptive-form/src/components/fields/StringField.tsx
  Composer/packages/adaptive-form/src/utils/resolveFieldWidget.ts
  Composer/packages/client/src/recoilModel/atoms/flowState.ts
  Composer/packages/client/src/recoilModel/atoms/index.ts
  Composer/packages/client/src/recoilModel/dispatchers/flow.ts
  Composer/packages/client/src/recoilModel/dispatchers/index.ts
  Composer/packages/client/src/shell/useShell.ts
  Composer/packages/extension-client/src/hooks/useApplicationApi.ts
  Composer/packages/extension-client/src/types/formSchema.ts
  Composer/packages/lib/ui-shared/src/components/IconMenu.tsx
  Composer/packages/lib/ui-shared/src/components/__tests__/IconMenu.test.tsx
  Composer/packages/lib/ui-shared/src/components/index.ts
  Composer/packages/lib/ui-shared/src/styled/styledComponents.tsx
  Composer/packages/test-utils/package.json
  Composer/packages/test-utils/src/index.ts
  Composer/packages/types/src/sdk.ts
  Composer/packages/types/src/shell.ts
  Composer/packages/ui-plugins/prompts/src/index.tsx
  Composer/yarn.lock
Labels: Team: Authoring

#8228 chore: Update orchestratorlib to 4.14.0-rc0
  Composer/packages/server/package.json
  Composer/yarn.lock
Labels: Area: Orchestrator
