Repository microsoft/BotFramework-Composer, pull requests merged in 2021-05, with the labels that each got.

#7534 fix: Add a QNA trigger to the dialog if it doesnt exist
  Composer/packages/client/src/pages/knowledge-base/QnAPage.tsx
  Composer/packages/client/src/recoilModel/dispatchers/trigger.ts
Labels: P0, ShipRoom-Approved

#7388 feat: Breaking change upgrade UX from 1.4 to 2.0
  Composer/packages/client/src/components/AppUpdater/AppUpdater.tsx
  Composer/packages/client/src/components/AppUpdater/breakingUpdates/breakingUpdatesMap.ts
  Composer/packages/client/src/components/AppUpdater/breakingUpdates/types.ts
  Composer/packages/client/src/components/AppUpdater/breakingUpdates/version1To2.tsx
  Composer/packages/client/src/components/AppUpdater/index.tsx
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/recoilModel/dispatchers/application.ts
  Composer/packages/electron-server/__tests__/appUpdater.test.ts
  Composer/packages/electron-server/src/appUpdater/appUpdater.ts
  Composer/packages/electron-server/src/appUpdater/breakingUpdates/index.ts
  Composer/packages/electron-server/src/appUpdater/breakingUpdates/types.ts
  Composer/packages/electron-server/src/appUpdater/breakingUpdates/version1To2.ts
  Composer/packages/electron-server/src/appUpdater/index.ts
  Composer/packages/electron-server/src/main.ts
  Composer/packages/server/src/locales/en-US.json
  Composer/packages/types/src/appUpdates.ts
  Composer/packages/types/src/index.ts
  releases/1.4.1.md
Labels: P0, Team: Runtime & Publishing

#7564 fix: Update attachment template format to support PVA
  Composer/packages/client/src/shell/utils.ts
  Composer/packages/lib/code-editor/src/lg/ModalityPivot.tsx
  Composer/packages/lib/code-editor/src/lg/constants.ts
  Composer/packages/lib/code-editor/src/lg/modalityEditors/AttachmentModalityEditor.tsx
  Composer/packages/lib/code-editor/src/utils/structuredResponse.ts
  Composer/packages/lib/shared/__tests__/lgUtils/stringBuilders/lgStringUtils.test.ts
  Composer/packages/lib/shared/src/lgUtils/index.ts
  Composer/packages/lib/shared/src/lgUtils/stringBuilders/lgStringUtils.ts
  Composer/packages/test-utils/src/react/jest.config.ts
  Composer/packages/ui-plugins/lg/src/LgWidget/useLgTemplate.ts
Labels: P0

#7567 fix: address a regression in the start bot button that caused final 'get started' bubb not to pop
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/Header.tsx
Labels: P0

#7554 fix: get tenant specific arm tokens for connections
  Composer/packages/client/src/pages/botProject/adapters/ABSChannels.tsx
Labels: P0

#7563 fix: Update provisionScript.zip with small syntax changes
  Provisioning/README.md
  Provisioning/provisionScripts.zip
Labels: P0

#7557 fix: Adjust build command used for dotnet functions
  extensions/azurePublish/src/node/provision.ts
  extensions/runtimes/src/index.ts
Labels: P0

#7599 fix: ui copy updates
  Composer/cypress/integration/DesignPage.spec.ts
  Composer/cypress/integration/LuisDeploy.spec.ts
  Composer/packages/client/src/components/GetStarted/GetStarted.tsx
  Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx
  Composer/packages/client/src/components/ManageLuis/ManageLuis.tsx
  Composer/packages/client/src/components/ManageQNA/ManageQNA.tsx
  Composer/packages/client/src/components/ManageService/ManageService.tsx
  Composer/packages/client/src/components/ManageSpeech/ManageSpeech.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
  Composer/packages/client/src/components/QnA/CreateQnAFromScratchModal.tsx
  Composer/packages/client/src/components/QnA/CreateQnAFromUrlModal.tsx
  Composer/packages/client/src/components/QnA/EditQnAFromUrlModal.tsx
  Composer/packages/client/src/components/QnA/ImportQnAFromUrlModal.tsx
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx
  Composer/packages/client/src/pages/botProject/BotProjectInfo.tsx
  Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
  Composer/packages/client/src/pages/botProject/BotProjectsSettingsTabView.tsx
  Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx
  Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
  Composer/packages/client/src/pages/botProject/SkillBotExternalService.tsx
  Composer/packages/client/src/pages/botProject/adapters/AdapterSection.tsx
  Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
  Composer/packages/client/src/utils/notifications.ts
  Composer/packages/server/src/locales/en-US.json
Labels: P0

#7648 chore: bump wait-on to v5.3.0
  Composer/package.json
  Composer/packages/server/package.json
  Composer/yarn.lock
  extensions/packageManager/package.json
  extensions/packageManager/yarn.lock
Labels: P0, ShipRoom-Approved

#6526 feat: detect "old" bots and migrate them to new runtime
  Composer/packages/client/src/components/CreationFlow/v2/CreationFlow.tsx
  Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx
  Composer/packages/client/src/constants.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsTabHeader.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/useAutoFix.ts
  Composer/packages/client/src/pages/diagnostics/types.ts
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/mocks/mockProjectResponse.json
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/recoilModel/selectors/diagnosticsPageSelector.ts
  Composer/packages/lib/indexers/__tests__/validations/schemaValidation/__mocks__/dialogMocks.ts
  Composer/packages/lib/indexers/__tests__/validations/schemaValidation/__mocks__/sdkSchema.ts
  Composer/packages/lib/indexers/__tests__/validations/schemaValidation/__mocks__/sdkSchemaMocks.ts
  Composer/packages/lib/indexers/__tests__/validations/schemaValidation/schemaUtils.test.ts
  Composer/packages/lib/indexers/__tests__/validations/schemaValidation/walkAdaptiveDialog.test.ts
  Composer/packages/lib/indexers/src/validations/index.ts
  Composer/packages/lib/indexers/src/validations/schemaValidation/index.ts
  Composer/packages/lib/indexers/src/validations/schemaValidation/schemaUtils.ts
  Composer/packages/lib/indexers/src/validations/schemaValidation/walkAdaptiveDialog.ts
  Composer/packages/server-workers/src/workers/templateInstallation.worker.ts
  Composer/packages/server/src/controllers/asset.ts
  Composer/packages/server/src/controllers/project.ts
  Composer/packages/server/src/locales/en-US.json
  Composer/packages/server/src/models/asset/assetManager.ts
  Composer/packages/server/src/models/bot/botProject.ts
  Composer/packages/server/src/models/bot/botStructure.ts
  Composer/packages/server/src/router/api.ts
  Composer/packages/server/src/services/project.ts
Labels: P0

#7678 chore: Rebase main with 1.4.1 release
  Composer/packages/client/src/components/AppUpdater/AppUpdater.tsx
  Composer/packages/client/src/components/AppUpdater/breakingUpdates/breakingUpdatesMap.ts
  Composer/packages/client/src/components/AppUpdater/breakingUpdates/types.ts
  Composer/packages/client/src/components/AppUpdater/breakingUpdates/version1To2.tsx
  Composer/packages/client/src/components/AppUpdater/index.tsx
  Composer/packages/client/src/constants.tsx
  Composer/packages/client/src/recoilModel/dispatchers/application.ts
  Composer/packages/electron-server/__tests__/appUpdater.test.ts
  Composer/packages/electron-server/src/appUpdater/appUpdater.ts
  Composer/packages/electron-server/src/appUpdater/breakingUpdates/index.ts
  Composer/packages/electron-server/src/appUpdater/breakingUpdates/types.ts
  Composer/packages/electron-server/src/appUpdater/breakingUpdates/version1To2.ts
  Composer/packages/electron-server/src/appUpdater/index.ts
  Composer/packages/electron-server/src/main.ts
  Composer/packages/types/src/appUpdates.ts
  Composer/packages/types/src/index.ts
  releases/1.4.1.md
Labels: P0

#7674 fix: Add components field to migrated settings.
  Composer/packages/server/src/services/project.ts
  extensions/packageManager/src/node/index.ts
Labels: P0

#7689 fix: (Un) Installing a package now stops the currently running bot beforehand
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/__tests__/BotRuntimeController/BotController.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
  Composer/packages/client/src/shell/useShell.ts
  Composer/packages/extension-client/src/hooks/useProjectApi.ts
  Composer/packages/types/src/shell.ts
  extensions/packageManager/src/pages/Library.tsx
Labels: P0

#7666 fix: generate manifest file when creating new publish target
  Composer/packages/client/src/pages/botProject/CreatePublishProfileDialog.tsx
  Composer/packages/client/src/pages/design/exportSkillModal/constants.tsx
  Composer/packages/client/src/pages/design/exportSkillModal/index.tsx
Labels: P0

#7824 fix: Throttle restart conversation
  Composer/packages/client/src/components/WebChat/WebChatHeader.tsx
  Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
  Composer/packages/client/src/components/WebChat/__tests__/WebChatHeader.test.tsx
Labels: P0

#7814 fix: Fix missing data collection settings on server
  Composer/packages/client/__tests__/routers.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/user.ts
  Composer/packages/client/src/telemetry/useInitializeLogger.ts
Labels: P0

#7782 fix: add inner scrollbar to selection area
  Composer/packages/client/src/pages/design/exportSkillModal/content/SelectItems.tsx
  Composer/packages/client/src/pages/design/exportSkillModal/index.tsx
  Composer/packages/client/src/pages/design/exportSkillModal/styles.ts
Labels: P0

#6633 fix: Remove depth and transparentBorders from FieldProps, remove ObjectArrayField, and refactor OpenObjectField
  Composer/packages/adaptive-form/src/components/AdaptiveForm.tsx
  Composer/packages/adaptive-form/src/components/AddButton.tsx
  Composer/packages/adaptive-form/src/components/CollapseField.tsx
  Composer/packages/adaptive-form/src/components/FormRow.tsx
  Composer/packages/adaptive-form/src/components/FormTitle.tsx
  Composer/packages/adaptive-form/src/components/SchemaField.tsx
  Composer/packages/adaptive-form/src/components/WithTypeIcons.tsx
  Composer/packages/adaptive-form/src/components/__tests__/FormRow.test.tsx
  Composer/packages/adaptive-form/src/components/__tests__/SchemaField.test.tsx
  Composer/packages/adaptive-form/src/components/fields/ArrayField.tsx
  Composer/packages/adaptive-form/src/components/fields/ArrayFieldItem.tsx
  Composer/packages/adaptive-form/src/components/fields/EditableField.tsx
  Composer/packages/adaptive-form/src/components/fields/ObjectArrayField.tsx
  Composer/packages/adaptive-form/src/components/fields/ObjectField.tsx
  Composer/packages/adaptive-form/src/components/fields/OneOfField/OneOfField.tsx
  Composer/packages/adaptive-form/src/components/fields/OneOfField/__tests__/OneOfField.test.tsx
  Composer/packages/adaptive-form/src/components/fields/OneOfField/utils.ts
  Composer/packages/adaptive-form/src/components/fields/OpenObjectField/ObjectItem.tsx
  Composer/packages/adaptive-form/src/components/fields/OpenObjectField/OpenObjectField.tsx
  Composer/packages/adaptive-form/src/components/fields/OpenObjectField/__tests__/OpenObjectField.test.tsx
  Composer/packages/adaptive-form/src/components/fields/OpenObjectField/styles.ts
  Composer/packages/adaptive-form/src/components/fields/StringField.tsx
  Composer/packages/adaptive-form/src/components/fields/UnsupportedField.tsx
  Composer/packages/adaptive-form/src/components/fields/__tests__/ArrayField.test.tsx
  Composer/packages/adaptive-form/src/components/fields/__tests__/ArrayFieldItem.test.tsx
  Composer/packages/adaptive-form/src/components/fields/__tests__/ObjectArrayField.test.tsx
  Composer/packages/adaptive-form/src/components/fields/__tests__/StringField.test.tsx
  Composer/packages/adaptive-form/src/components/fields/__tests__/testUtils.ts
  Composer/packages/adaptive-form/src/components/fields/index.ts
  Composer/packages/adaptive-form/src/components/fields/styles.ts
  Composer/packages/adaptive-form/src/utils/__tests__/resolveFieldWidget.test.ts
  Composer/packages/adaptive-form/src/utils/arrayUtils.ts
  Composer/packages/adaptive-form/src/utils/resolveFieldWidget.ts
  Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx
  Composer/packages/extension-client/src/types/form.ts
  Composer/packages/ui-plugins/schema-editor/src/__tests__/SchemaEditorField.test.tsx
  Composer/packages/ui-plugins/select-dialog/src/DialogOptionsField.tsx
Labels: Area: Form Editor, R14

#7775 fix: Custom function declaration
  Composer/packages/server/src/services/project.ts
Labels: R14
