Repository microsoft/BotFramework-Composer, pull requests merged in 2021-04, with the labels that each got.

#5881 feat: enable new creation flow as default
  .vscode/launch.json
  Composer/cypress/integration/CreateNewBot.spec.ts
  Composer/cypress/integration/HomePage.spec.ts
  Composer/cypress/integration/NavigateUrls.spec.ts
  Composer/packages/client/__tests__/components/CreationFlow/index.test.tsx
  Composer/packages/client/__tests__/components/CreationFlowV2/CreateOptions/index.test.tsx
  Composer/packages/client/__tests__/components/CreationFlowV2/index.test.tsx
  Composer/packages/client/src/components/CreationFlow/CreateOptions.tsx
  Composer/packages/client/src/components/CreationFlow/CreationFlow.tsx
  Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx
  Composer/packages/client/src/components/CreationFlow/v2/CreateOptions.tsx
  Composer/packages/client/src/components/CreationFlow/v2/CreationFlow.tsx
  Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/pages/botProject/BotProjectSettingsTableView.tsx
  Composer/packages/client/src/pages/botProject/BotProjectsSettingsTabView.tsx
  Composer/packages/client/src/pages/design/creationModal.tsx
  Composer/packages/client/src/pages/home/Home.tsx
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/recoilModel/selectors/extensions.ts
  Composer/packages/lib/shared/src/featureFlagUtils/index.ts
  Composer/packages/server-workers/src/workers/templateInstallation.worker.ts
  Composer/packages/server/src/controllers/asset.ts
  Composer/packages/server/src/locales/en-US.json
  Composer/packages/server/src/models/asset/__tests__/assetManager.test.ts
  Composer/packages/server/src/models/asset/assetManager.ts
  Composer/packages/server/src/services/project.ts
  Composer/packages/server/src/utility/__tests__/creation.test.ts
  Composer/packages/server/src/utility/creation.ts
  Composer/packages/types/src/creation.ts
  Composer/packages/types/src/featureFlags.ts
  Composer/packages/types/src/runtime.ts
  azure-pipelines.yml
  extensions/azurePublish/src/components/azureProvisionDialog.tsx
  extensions/azurePublish/src/components/images/QnA-Maker.svg
  extensions/azurePublish/src/node/deploy.ts
  extensions/packageManager/package.json
  extensions/packageManager/src/node/index.ts
  extensions/packageManager/src/pages/Library.tsx
  extensions/packageManager/yarn.lock
  extensions/runtimes/src/index.ts
Labels: topic: creation

#6673 feat: Runtime Logs Viewer
  .vscode/launch.json
  Composer/cypress/integration/LuisDeploy.spec.ts
  Composer/packages/client/__tests__/components/BotRuntimeController/errorCallout.test.tsx
  Composer/packages/client/__tests__/components/BotRuntimeController/errorInfo.test.tsx
  Composer/packages/client/package.json
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotControllerMenu.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotErrorViewer.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotStatusIndicator.tsx
  Composer/packages/client/src/components/BotRuntimeController/ErrorCallout.tsx
  Composer/packages/client/src/components/BotRuntimeController/ErrorInfo.tsx
  Composer/packages/client/src/components/DiagnosticsHeader.tsx
  Composer/packages/client/src/components/Header.tsx
  Composer/packages/client/src/components/__tests__/BotRuntimeController/BotStatusIndicator.test.tsx
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/pages/design/DebugPanel/DebugPanel.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/index.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/BotProjectsFilter.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/OutputsTabContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/OutputsTabLogHeader.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/RuntimeOutputLog.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/index.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogItem.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/config.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/index.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/types.ts
  Composer/packages/client/src/pages/design/__tests__/RuntimeOutputLog.test.tsx
  Composer/packages/client/src/recoilModel/atoms/botState.ts
  Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/packages/types/src/publish.ts
  Composer/packages/types/src/telemetry.ts
  Composer/yarn.lock
  extensions/localPublish/src/index.ts
Labels: Webchat Integration

#6668 chore: Update bf-orchestrator to 4.13.0-rc0
  Composer/packages/server/package.json
  Composer/yarn.lock
Labels: Area: Orchestrator, P1

#6667 fix: Orchestrator worker crashes if accessing getLabelResolversAsync concurrently
  Composer/packages/server/src/models/bot/__tests__/orchestratorWorker.test.ts
  Composer/packages/server/src/models/bot/process/orchestratorWorker.ts
Labels: Area: Orchestrator, P0

#6638 feat: Added network and activity logs to Web Chat log panel
  Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
  Composer/packages/client/src/components/WebChat/utils/conversationService.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/LogItemHelpers.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatActivityLogItem.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatInspectorPane.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatLogContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatLogItemHeader.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatNetworkLogItem.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/config.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/logItemStyles.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogItem.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/index.ts
  Composer/packages/client/src/pages/design/__tests__/DebugPanel.test.tsx
  Composer/packages/client/src/pages/design/__tests__/WebChatLogContent.test.tsx
  Composer/packages/client/src/pages/design/__tests__/WebChatLogItemHeader.test.tsx
  Composer/packages/client/src/recoilModel/atoms/botState.ts
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/webchat.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/webchat.ts
  Composer/packages/client/src/recoilModel/types.ts
  Composer/packages/lib/code-editor/src/BaseEditor.tsx
  Composer/packages/lib/code-editor/src/JsonEditor.tsx
  Composer/packages/server/src/directline/middleware/__tests__/attachmentHandler.test.ts
  Composer/packages/server/src/directline/middleware/__tests__/conversationHandler.test.ts
  Composer/packages/server/src/directline/middleware/__tests__/createUploadHandler.test.ts
  Composer/packages/server/src/directline/middleware/conversationHandler.ts
  Composer/packages/server/src/directline/middleware/createUploadHandler.ts
  Composer/packages/server/src/directline/middleware/transcriptHandler.ts
  Composer/packages/server/src/directline/mountAttachmentRoutes.ts
  Composer/packages/server/src/directline/mountConversationRoutes.ts
  Composer/packages/server/src/directline/mountDirectlineRoutes.ts
  Composer/packages/server/src/directline/store/dlServerState.ts
  Composer/packages/server/src/directline/store/types.ts
  Composer/packages/server/src/directline/utils/__tests__/helpers.test.ts
  Composer/packages/server/src/directline/utils/__tests__/mountAttachmentRoutes.test.ts
  Composer/packages/server/src/directline/utils/apiErrorException.ts
  Composer/packages/server/src/directline/utils/helpers.ts
  Composer/packages/server/src/directline/utils/webSocketServer.ts
  Composer/packages/server/src/middleware/__tests__/logNetworkTraffic.test.ts
  Composer/packages/server/src/middleware/logNetworkTraffic.ts
  Composer/packages/server/src/server.ts
  Composer/packages/types/package.json
  Composer/packages/types/src/server.ts
  Composer/packages/types/src/settings.ts
Labels: Webchat Integration

#6786 feat: Use websocket to continuously surface runtime log into the UI
  Composer/packages/client/package.json
  Composer/packages/client/src/components/BotRuntimeController/BotErrorViewer.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotRuntimeStatus.tsx
  Composer/packages/client/src/components/BotRuntimeController/ErrorCallout.tsx
  Composer/packages/client/src/components/BotRuntimeController/useBotOperations.ts
  Composer/packages/client/src/components/__tests__/BotRuntimeController/BotRuntimeStatus.test.tsx
  Composer/packages/client/src/components/__tests__/BotRuntimeController/BotStatusIndicator.test.tsx
  Composer/packages/client/src/components/__tests__/BotRuntimeController/useBotOperations.test.tsx
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/OutputTabContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/OutputTabLogHeader.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/RuntimeOutputLog.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/index.ts
  Composer/packages/client/src/pages/design/__tests__/RuntimeOutputLog.test.tsx
  Composer/packages/client/src/recoilModel/atoms/botState.ts
  Composer/packages/client/src/recoilModel/dispatchers/builder.ts
  Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
  Composer/packages/client/src/recoilModel/types.ts
  Composer/packages/client/src/utils/runtimeErrors.ts
  Composer/packages/server/src/controllers/publisher.ts
  Composer/packages/server/src/router/api.ts
  Composer/packages/types/src/publish.ts
  Composer/yarn.lock
  extensions/localPublish/package.json
  extensions/localPublish/src/index.ts
  extensions/localPublish/src/runtimeLogServer.ts
  extensions/localPublish/yarn.lock
Labels: P0, Webchat Integration

#6835 fix: lu language server
  Composer/packages/tools/language-servers/language-understanding/src/luParser.ts
Labels: Area: LU

#6782 feat: Added selected state to Web Chat log panel and auto-inspection on load
  Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatLogContent.tsx
  Composer/packages/client/src/pages/design/__tests__/WebChatLogContent.test.tsx
  Composer/packages/client/src/pages/design/__tests__/WebChatLogItemHeader.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/__tests__/webchat.test.tsx
  Composer/packages/client/src/recoilModel/dispatchers/webchat.ts
  Composer/packages/server/src/middleware/logNetworkTraffic.ts
  Composer/packages/types/src/server.ts
Labels: Webchat Integration

#6870 feat: Move Debug Panel outside the main content container
  Composer/packages/client/src/components/Page.tsx
  Composer/packages/client/src/pages/design/DebugPanel/DebugPanel.tsx
  Composer/packages/client/src/pages/design/DebugPanel/styles.ts
  Composer/packages/client/src/pages/design/DesignPage.tsx
Labels: Webchat Integration

#6878 fix: misc UI fixes around creation and config
  Composer/packages/client/src/components/LoadingSpinner.tsx
  Composer/packages/client/src/components/ManageLuis/ManageLuis.tsx
  Composer/packages/client/src/components/ManageQNA/ManageQNA.tsx
  Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
  Composer/packages/client/src/pages/design/VisualPanel.tsx
  Composer/packages/client/src/router.tsx
  Composer/packages/server-workers/src/workers/templateInstallation.worker.ts
  extensions/azurePublish/src/components/api.tsx
Labels: topic: creation

#6992 fix: Route to appsettings correctly
  Composer/packages/client/src/pages/botProject/BotProjectsSettingsTabView.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticList.tsx
  Composer/packages/client/src/pages/diagnostics/Diagnostics.tsx
  Composer/packages/client/src/pages/diagnostics/types.ts
  Composer/packages/electron-server/src/main.ts
Labels: Webchat Integration

#6724 feature: new design for Connections setting pane
  Composer/packages/client/__tests__/pages/botProjectsSettings/AdapterSettings.test.tsx
  Composer/packages/client/src/pages/botProject/adapters/ABSChannels.tsx
  Composer/packages/client/src/pages/botProject/adapters/AdapterSection.tsx
  Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx
  Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterSettings.tsx
  Composer/packages/client/src/pages/botProject/styles.ts
  Composer/packages/server/src/locales/en-US.json
Labels: Area: Adapters

#7030 fix: Prevent Runtime log for skills from being swallowed when switching between projects
  Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/OutputTabContent.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/RuntimeOutputLog.tsx
  Composer/packages/client/src/pages/design/__tests__/OutputTabContent.test.tsx
  Composer/packages/electron-server/locales/en-US.json
Labels: Webchat Integration

#7004 fix: Update OnChooseIntent template to support Orchestrator
  Composer/packages/client/src/recoilModel/dispatchers/trigger.ts
  Composer/packages/lib/indexers/src/utils/lgUtil.ts
  Composer/packages/lib/shared/src/constant.ts
  Composer/packages/lib/shared/src/dialogFactory.ts
Labels: Area: Orchestrator

#7119 feat: diable /hide items when in PVA bot context
  Composer/packages/adaptive-form/src/components/fields/RecognizerField/getDropdownOptions.ts
  Composer/packages/client/src/components/AppComponents/SideBar.tsx
  Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
  Composer/packages/client/src/components/DisableFeatureToolTip.tsx
  Composer/packages/client/src/components/Header.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectHeader.tsx
  Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx
  Composer/packages/client/src/components/__tests__/DisableFeatureToolTip.test.tsx
  Composer/packages/client/src/hooks/usePVACheck.ts
  Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
  Composer/packages/client/src/pages/botProject/BotProjectsSettingsTabView.tsx
  Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
  Composer/packages/client/src/pages/design/SideBar.tsx
  Composer/packages/client/src/recoilModel/selectors/project.ts
  Composer/packages/client/src/utils/pageLinks.ts
Labels: Area: PVA

#7241 fix: Empty Webchat inspector text and Disabling items in PVA context
  Composer/packages/client/src/components/BotRuntimeController/ErrorCallout.tsx
  Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx
  Composer/packages/client/src/components/GetStarted/GetStartedTask.tsx
  Composer/packages/client/src/components/GetStarted/types.ts
  Composer/packages/client/src/components/NavItem.tsx
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatLogContent.tsx
Labels: Webchat Integration

#7258 feat: Move Webchat Panel inside the Page section to prevent overlap over Debug Pane
  Composer/cypress/integration/NotificationPage.spec.ts
  Composer/packages/client/src/components/Header.tsx
  Composer/packages/client/src/components/NavTree.tsx
  Composer/packages/client/src/components/Page.tsx
  Composer/packages/client/src/components/WebChat/WebChatComposer.tsx
  Composer/packages/client/src/components/WebChat/WebChatContainer.tsx
  Composer/packages/client/src/components/WebChat/WebChatHeader.tsx
  Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
  Composer/packages/client/src/components/WebChat/__tests__/WebChat.test.tsx
  Composer/packages/client/src/components/WebChat/__tests__/WebChatHeader.test.tsx
  Composer/packages/client/src/components/WebChat/type.ts
  Composer/packages/client/src/components/WebChat/types.ts
  Composer/packages/client/src/components/WebChat/utils/conversationService.ts
  Composer/packages/client/src/components/__tests__/useDebugPane.test.ts
  Composer/packages/client/src/components/useDebugPane.ts
  Composer/packages/client/src/pages/design/DebugPanel/DebugPanel.tsx
  Composer/packages/client/src/pages/design/DesignPage.tsx
  Composer/packages/client/src/pages/design/styles.ts
  Composer/packages/client/src/pages/knowledge-base/QnAPage.tsx
  Composer/packages/client/src/pages/language-generation/LGPage.tsx
  Composer/packages/client/src/pages/language-understanding/LUPage.tsx
  Composer/packages/client/src/router.tsx
  Composer/packages/client/src/utils/pageLinks.ts
  Composer/packages/client/src/utils/zIndices.ts
  Composer/packages/server/src/locales/en-US.json
Labels: Webchat Integration

#7386 chore: Remove LUIS text from Trigger Dialog
  Composer/packages/client/src/components/TriggerCreationModal/resolveTriggerWidget.tsx
  Composer/packages/server/src/locales/en-US.json
Labels: Area: Orchestrator, P2

#7378 fix: various template bugs
  Composer/packages/client/__tests__/components/CreationFlowV2/index.test.tsx
  Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx
  Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx
  Composer/packages/server/src/controllers/asset.ts
  Composer/packages/server/src/utility/__tests__/creation.test.ts
  Composer/packages/server/src/utility/creation.ts
Labels: P0

#7407 fix: use feature-specific tags rather than msbot-component
  extensions/packageManager/src/node/index.ts
Labels: P0

#7430 fix: Add a warning about the luis authoring key 1000/month limit
  Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
Labels: P0

#7418 fix: UI fixes in getting started rocket panel
  Composer/packages/client/__tests__/components/CreationFlowV2/index.test.tsx
  Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx
  Composer/packages/client/src/components/GetStarted/GetStarted.tsx
  Composer/packages/client/src/components/GetStarted/GetStartedLearn.tsx
  Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx
  Composer/packages/client/src/components/GetStarted/GetStartedTask.tsx
  Composer/packages/client/src/components/GetStarted/styles.ts
Labels: P0, topic: creation

#7419 fix: bump bf-dialog to 4.13.1
  Composer/packages/server-workers/package.json
  Composer/packages/server-workers/yarn.lock
  Composer/packages/server/package.json
  Composer/yarn.lock
  extensions/packageManager/package.json
  extensions/packageManager/yarn.lock
Labels: P0

#7482 chore: Temporarily removes save as button for R13
  Composer/cypress/integration/HomePage.spec.ts
  Composer/packages/client/src/pages/home/Home.tsx
Labels: P0

#7429 fix: fixes notification container blocking interaction
  Composer/packages/client/src/components/Notifications/NotificationCard.tsx
  Composer/packages/client/src/components/Notifications/NotificationContainer.tsx
Labels: P0

#7484 fix: Add Publish your bot to get started list
  Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx
Labels: P0

#7488 fix: update gitignore, detect missing func runtime
  Composer/packages/client/src/constants.ts
  Composer/packages/client/src/pages/home/Home.tsx
  Composer/packages/client/src/recoilModel/atoms/appState.ts
  Composer/packages/client/src/recoilModel/dispatchers/project.ts
  Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
  Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
  Composer/packages/client/src/utils/runtimeErrors.ts
  Composer/packages/server/src/services/project.ts
  Composer/packages/types/src/telemetry.ts
  extensions/samples/assets/shared/.gitignore
Labels: P0

#7514 fix: Check for webchat panel visibility
  Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatLogContent.tsx
Labels: P0, Webchat Integration
